//! Regressions found by the DevRel review of 2026-09-24.
//!
//! Finding ids (`F1`…`F22`) are the review's, kept so a failure here points at
//! the write-up in `evnx-devrel-review/`.
//!
//! # Why these live together rather than in each command's file
//!
//! The review's central finding is not about any one command:
//!
//! > Every file evnx generates or repairs must pass every other evnx command.
//!
//! Three separate bugs violated it — `init` wrote a `.env.example` that a manual
//! append silently destroyed, `init --with postgresql` wrote a `DATABASE_URL`
//! that `validate --validate-formats` rejected, and `validate --fix` wrote a
//! `SECRET_KEY` that `scan` flagged. Each looked local. Together they meant a
//! user following evnx's own advice could not reach a green state.
//!
//! A test that spans commands has to live somewhere that belongs to none of
//! them.

use assert_cmd::cargo::cargo_bin_cmd;
use std::fs;
use tempfile::TempDir;

/// `init` needs a git repo to make its `.gitignore` judgements.
fn project() -> TempDir {
    let dir = TempDir::new().unwrap();
    std::process::Command::new("git")
        .args(["init", "-q"])
        .current_dir(dir.path())
        .status()
        .expect("git init");
    dir
}

// ── F20 — the file init writes must survive being appended to ───────────────

/// ⚠️ `init` wrote `.env.example` with **no trailing newline**, so the next line
/// appended to it fused onto the final comment:
///
/// ```text
/// # Generated by evnx v0.5.0 on 2026-09-24 02:08APPENDED_VAR=x
/// ```
///
/// dotenv reads that as a comment, so the variable silently disappears.
///
/// `evnx add` was immune — its writer trims and re-adds the newline — which is
/// why the bug survived: evnx's own documented next step hid it, and only a hand
/// edit or another tool was affected.
#[test]
fn f20_init_writes_a_file_that_can_be_appended_to() {
    let dir = project();

    cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["init", "--yes", "--with", "postgresql"])
        .assert()
        .success();

    let example = dir.path().join(".env.example");
    let body = fs::read_to_string(&example).unwrap();
    assert!(
        body.ends_with('\n'),
        ".env.example must end with a newline; last 60 bytes: {:?}",
        &body[body.len().saturating_sub(60)..]
    );

    // The property that actually matters: an append is a separate line.
    fs::write(&example, format!("{body}APPENDED_VAR=x\n")).unwrap();
    let after = fs::read_to_string(&example).unwrap();
    assert!(
        after.lines().any(|l| l.trim() == "APPENDED_VAR=x"),
        "the appended variable was swallowed:\n{after}"
    );
}

// ── F21 — a repair that succeeds must not report failure ────────────────────

/// ⚠️ `validate --fix` counted the issues it found on entry and never recounted,
/// so it repaired everything and then exited 1 — reporting the problems it had
/// just removed. `evnx validate --fix && deploy` never reached `deploy`, while
/// the next plain `validate` exited 0.
#[test]
fn f21_validate_fix_exits_0_when_it_fixed_everything() {
    let dir = TempDir::new().unwrap();
    fs::write(dir.path().join(".env"), "A=1\n").unwrap();
    fs::write(dir.path().join(".env.example"), "A=\nB=\n").unwrap();

    cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["validate", "--fix"])
        .assert()
        .code(0);

    // And the complement: a problem `--fix` cannot repair must still be 1, or
    // the guard above would have been satisfiable by never failing.
    let dir2 = TempDir::new().unwrap();
    fs::write(dir2.path().join(".env"), "A=1\n").unwrap();
    fs::write(dir2.path().join(".env.example"), "A=\nB=\nC=\n").unwrap();
    fs::write(
        dir2.path().join(".evnx.toml"),
        "[vars]\nC = { format = \"port\" }\n",
    )
    .unwrap();
    let assert = cargo_bin_cmd!("evnx")
        .current_dir(dir2.path())
        .args(["validate"])
        .assert();
    let code = assert.get_output().status.code().unwrap();
    assert!(code == 1, "unfixed problems must still exit 1, got {code}");
}

// ── completions — an error is 2, in every command ───────────────────────────

/// ⚠️ `completions` called `process::exit(1)` directly, bypassing the
/// centralised mapping `main` gained in v0.5.0. So it was the one command that
/// answered an unusable argument with 1 — the code every other command reserves
/// for a real finding.
#[test]
fn completions_rejects_an_unknown_shell_with_2() {
    let assert = cargo_bin_cmd!("evnx")
        .args(["completions", "tcsh"])
        .assert()
        .code(2);

    let stderr = String::from_utf8_lossy(&assert.get_output().stderr).to_string();
    assert!(stderr.contains("No verdict"), "{stderr}");
    assert!(
        stderr.contains("bash"),
        "the error should name the valid shells: {stderr}"
    );
}

#[test]
fn completions_still_generates_for_a_known_shell() {
    for shell in ["bash", "zsh", "fish", "powershell"] {
        let assert = cargo_bin_cmd!("evnx")
            .args(["completions", shell])
            .assert()
            .code(0);
        assert!(
            !assert.get_output().stdout.is_empty(),
            "{shell} produced no completion script"
        );
    }
}

// ── F1/F2 — evnx must not reject the files evnx writes ──────────────────────

/// ⚠️ `--validate-formats` used `^https?://…`, so every `postgresql://`,
/// `redis://` and `amqp://` value was *"not a valid URL"* — including the
/// `DATABASE_URL` that `evnx init --with postgresql` had just written.
///
/// This is the review's structural finding in its clearest form: a tool that
/// generates a file its own validator rejects sends the user in a circle.
#[test]
fn f2_what_init_writes_passes_validate() {
    let dir = project();

    cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["init", "--yes", "--with", "postgresql,redis"])
        .assert()
        .success();

    let assert = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["validate", "--validate-formats", "--exit-zero"])
        .assert();
    let out = String::from_utf8_lossy(&assert.get_output().stdout).to_string();

    assert!(
        !out.contains("valid URL"),
        "evnx rejected a URL it wrote itself:\n{out}"
    );
}

/// The complement: a value that genuinely is not a URL must still be reported,
/// or the fix above would have been "accept everything".
#[test]
fn f1_a_real_non_url_is_still_reported() {
    let dir = TempDir::new().unwrap();
    fs::write(dir.path().join(".env"), "API_URL=not-a-url\n").unwrap();
    fs::write(dir.path().join(".env.example"), "API_URL=\n").unwrap();

    let assert = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["validate", "--validate-formats", "--exit-zero"])
        .assert();
    let out = String::from_utf8_lossy(&assert.get_output().stdout).to_string();

    assert!(out.contains("valid URL"), "expected a complaint:\n{out}");
}

// ── F3/F4 — doctor and the core parser must agree ───────────────────────────

/// ⚠️ `doctor` carries its own line-syntax regex, separate from `core::Parser`.
/// It omitted the optional `export` prefix, so `export FOO=bar` — which the
/// parser documents as supported and strips at `parser.rs:385` — was reported
/// as *"invalid syntax"* while `evnx validate` on the same file found zero
/// errors.
///
/// The duplication cannot simply be deleted: the parser stops at its first
/// error and `doctor` must report every bad line. So this test is what keeps
/// the two honest — it runs both over the same corpus and requires the same
/// verdict.
#[test]
fn doctor_agrees_with_the_parser_about_what_is_valid() {
    use evnx::core::Parser;

    // (line, is it valid?)
    let corpus = [
        ("KEY=value", true),
        ("export KEY=value", true),
        ("export   KEY=value", true),
        ("# a comment", true),
        ("   # indented comment", true),
        ("", true),
        ("   ", true),
        ("KEY=", true),
        ("  KEY  =  value", true),
        ("_UNDERSCORE_START=1", true),
        ("not-a-line", false),
        ("KEY value", false),
    ];

    let parser = Parser::default();

    for (line, expected_valid) in corpus {
        let dir = TempDir::new().unwrap();
        fs::write(dir.path().join(".gitignore"), ".env*\n").unwrap();
        fs::write(dir.path().join(".env"), format!("{line}\n")).unwrap();

        let assert = cargo_bin_cmd!("evnx")
            .current_dir(dir.path())
            .args(["doctor"])
            .assert();
        let out = String::from_utf8_lossy(&assert.get_output().stdout).to_string();
        let doctor_ok = !out.contains("invalid syntax");

        let parser_ok = parser.parse_content(&format!("{line}\n")).is_ok();

        assert_eq!(
            doctor_ok,
            parser_ok,
            "doctor and the parser disagree about {line:?} — doctor says {}, parser says {}",
            if doctor_ok { "valid" } else { "invalid" },
            if parser_ok { "valid" } else { "invalid" },
        );
        assert_eq!(
            doctor_ok,
            expected_valid,
            "{line:?} should be {}",
            if expected_valid { "valid" } else { "invalid" }
        );
    }
}

/// ⚠️ `validate_env_syntax` returned on the first bad line, so a file with three
/// problems took three `doctor` runs to diagnose.
#[test]
fn f4_doctor_reports_every_bad_line_not_just_the_first() {
    let dir = TempDir::new().unwrap();
    fs::write(dir.path().join(".gitignore"), ".env*\n").unwrap();
    fs::write(
        dir.path().join(".env"),
        "GOOD=1\n!!bad one\nALSO_GOOD=2\n@@bad two\n# fine\n%%bad three\n",
    )
    .unwrap();

    let assert = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["doctor"])
        .assert();
    let out = String::from_utf8_lossy(&assert.get_output().stdout).to_string();

    for line in ["Line 2", "Line 4", "Line 6"] {
        assert!(out.contains(line), "{line} was not reported:\n{out}");
    }
}

// ── F6 — the same input must produce the same output ────────────────────────

/// ⚠️ `check_missing_variables` and `check_extra_variables` built two
/// `HashSet`s and reported `difference()`. Rust seeds its hasher randomly per
/// process, so five consecutive runs over one file gave five orderings.
///
/// That makes output undiffable, defeats any golden file covering more than one
/// finding, and makes a reader ask what changed when nothing did.
///
/// ⚠️ The existing golden fixtures could not catch this: none has more than one
/// missing variable, and one item cannot be out of order. This uses five.
#[test]
fn f6_validate_reports_findings_in_a_stable_order() {
    let dir = TempDir::new().unwrap();
    fs::write(dir.path().join(".env.example"), "A=\nB=\nC=\nD=\nE=\n").unwrap();
    fs::write(dir.path().join(".env"), "A=1\n").unwrap();

    let order = |_| -> String {
        let assert = cargo_bin_cmd!("evnx")
            .current_dir(dir.path())
            .args(["validate", "--format", "json", "--exit-zero"])
            .assert();
        let v: serde_json::Value =
            serde_json::from_slice(&assert.get_output().stdout).expect("json");
        v["issues"]
            .as_array()
            .unwrap()
            .iter()
            .map(|i| i["variable"].as_str().unwrap_or("?").to_string())
            .collect::<Vec<_>>()
            .join(",")
    };

    let first = order(0);
    for run in 1..8 {
        assert_eq!(
            order(run),
            first,
            "run {run} reported a different order; the first was {first}"
        );
    }

    // And it is the order of `.env.example`, which is the file the reader has
    // open — not merely *an* order.
    assert_eq!(first, "B,C,D,E");
}

/// `sync` writes this order into `.env.example`, so a random one meant two
/// developers syncing the same `.env` produced two different files.
#[test]
fn f6_sync_writes_variables_in_the_order_they_appear() {
    let dir = TempDir::new().unwrap();
    fs::write(
        dir.path().join(".env"),
        "ZULU=1\nYANKEE=2\nXRAY=3\nWHISKEY=4\n",
    )
    .unwrap();

    let mut seen = std::collections::HashSet::new();
    for _ in 0..5 {
        let _ = fs::remove_file(dir.path().join(".env.example"));
        cargo_bin_cmd!("evnx")
            .current_dir(dir.path())
            .args(["sync", "--direction", "forward", "--placeholder"])
            .assert()
            .success();
        let body = fs::read_to_string(dir.path().join(".env.example")).unwrap();
        let order: Vec<&str> = body
            .lines()
            .filter_map(|l| l.split('=').next())
            .filter(|k| !k.trim().is_empty() && !k.starts_with('#'))
            .collect();
        seen.insert(order.join(","));
    }

    assert_eq!(seen.len(), 1, "sync wrote more than one ordering: {seen:?}");
    assert_eq!(
        seen.into_iter().next().unwrap(),
        "ZULU,YANKEE,XRAY,WHISKEY",
        "the order should be the one in .env"
    );
}

// ── F5 — a key written twice must not vanish in silence ─────────────────────

/// ⚠️ The parser builds an `IndexMap`, and `insert` overwrites — so
/// `API_KEY=first` followed by `API_KEY=second` silently became `second` and
/// nothing reported it. Last-wins is kept, because that is what dotenv
/// implementations do; the silence is what changed.
#[test]
fn f5_duplicate_keys_are_reported() {
    let dir = TempDir::new().unwrap();
    fs::write(
        dir.path().join(".env"),
        "API_KEY=first\nOTHER=x\nAPI_KEY=second\nexport OTHER=y\n",
    )
    .unwrap();
    fs::write(dir.path().join(".env.example"), "API_KEY=\nOTHER=\n").unwrap();

    let assert = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["validate", "--exit-zero"])
        .assert();
    let out = String::from_utf8_lossy(&assert.get_output().stdout).to_string();

    assert!(out.contains("API_KEY is assigned 2 times"), "{out}");
    assert!(
        out.contains("lines 1, 3"),
        "the report should name where: {out}"
    );
    // `export OTHER=y` is the same variable as `OTHER=x`.
    assert!(out.contains("OTHER is assigned 2 times"), "{out}");

    // Parsing is unchanged: the last assignment still wins.
    let converted = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["convert", "--to", "json"])
        .assert()
        .success();
    let v: serde_json::Value = serde_json::from_slice(&converted.get_output().stdout).unwrap();
    assert_eq!(v["API_KEY"], "second");
    assert_eq!(v["OTHER"], "y");
}

#[test]
fn f5_a_file_without_duplicates_is_silent() {
    let dir = TempDir::new().unwrap();
    fs::write(dir.path().join(".env"), "A=1\nB=2\n").unwrap();
    fs::write(dir.path().join(".env.example"), "A=\nB=\n").unwrap();

    let assert = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["validate"])
        .assert();
    let out = String::from_utf8_lossy(&assert.get_output().stdout).to_string();
    assert!(!out.contains("assigned"), "false positive:\n{out}");
}

// ── F8 — SARIF that GitHub can actually track ───────────────────────────────

/// ⚠️ The `ruleId` was the whole display name, so the key-name heuristic
/// produced `secret/sensitive-config-key:-acme_internal_token` — **the variable
/// name inside the rule id**. Every new variable was a new rule to GitHub, so
/// the rules list grew without bound, a dismissed alert never stayed dismissed,
/// and two runs of the same scan shared no rules at all.
///
/// There was also no `rules[]` (GitHub shows a bare id with no help link) and no
/// fingerprints (alerts are tracked by line number, so inserting a line above a
/// secret closes one alert and opens another).
#[test]
fn f8_sarif_rule_ids_identify_the_kind_not_the_instance() {
    let dir = TempDir::new().unwrap();
    fs::write(
        dir.path().join(".env"),
        "AWS_ACCESS_KEY_ID=AKIA4OZRMFJ3VREALKEY\n\
         ACME_INTERNAL_TOKEN=a-long-configuration-value-here\n\
         OTHER_SECRET_THING=another-long-configuration-value\n",
    )
    .unwrap();

    let assert = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["scan", ".env", "--format", "sarif", "--exit-zero"])
        .assert()
        .code(0);
    let doc: serde_json::Value = serde_json::from_slice(&assert.get_output().stdout).unwrap();
    let run = &doc["runs"][0];

    let rule_ids: Vec<&str> = run["tool"]["driver"]["rules"]
        .as_array()
        .expect("rules[] must exist — GitHub has no rule metadata without it")
        .iter()
        .map(|r| r["id"].as_str().unwrap())
        .collect();

    for id in &rule_ids {
        assert!(
            !id.contains("acme") && !id.contains("other_secret"),
            "a variable name leaked into a rule id: {id}"
        );
    }

    // Two findings of the same kind share one rule.
    let results = run["results"].as_array().unwrap();
    assert_eq!(results.len(), 3, "expected three findings");
    assert!(
        rule_ids.len() < results.len(),
        "three findings produced {} rules — ids are still per-instance: {rule_ids:?}",
        rule_ids.len()
    );

    // Every rule carries a help link.
    for rule in run["tool"]["driver"]["rules"].as_array().unwrap() {
        assert!(rule["helpUri"].is_string(), "rule without helpUri: {rule}");
    }

    // Every result carries a fingerprint, and they are distinct.
    let prints: Vec<&str> = results
        .iter()
        .map(|r| {
            r["partialFingerprints"]["evnxSecretV1"]
                .as_str()
                .expect("every result needs a fingerprint")
        })
        .collect();
    let unique: std::collections::HashSet<&&str> = prints.iter().collect();
    assert_eq!(
        unique.len(),
        prints.len(),
        "fingerprints collided: {prints:?}"
    );
}

// ── F11 — a missing required argument is not a licence to guess ─────────────

/// ⚠️ `select_destination` ended `.interact().unwrap_or(0)`. With no terminal —
/// every CI runner — it **silently selected the first destination in the list**,
/// so `evnx migrate --dry-run` printed a plan for somewhere the user had never
/// chosen and exited 0.
#[test]
fn f11_migrate_without_a_destination_refuses_rather_than_guessing() {
    let dir = TempDir::new().unwrap();
    fs::write(dir.path().join(".env"), "A=1\n").unwrap();

    let assert = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["migrate", "--dry-run"])
        .assert()
        .code(2);
    let stderr = String::from_utf8_lossy(&assert.get_output().stderr).to_string();
    assert!(stderr.contains("--to is required"), "{stderr}");
    assert!(
        stderr.contains("github-actions"),
        "the error should list what is available: {stderr}"
    );

    // Naming one still works.
    cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["migrate", "--to", "github-actions", "--dry-run"])
        .assert()
        .code(0);
}

// ── F19 — --detect already implies --yes ────────────────────────────────────

#[test]
fn f19_detect_and_yes_are_not_in_conflict() {
    let dir = project();
    fs::write(
        dir.path().join("package.json"),
        r#"{"dependencies":{"next":"14"}}"#,
    )
    .unwrap();

    cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["init", "--detect", "--yes"])
        .assert()
        .code(0);

    assert!(dir.path().join(".env.example").exists());
}

// ── F16 — a flag with no description is a flag nobody can use ───────────────

/// ⚠️ Fourteen flags across `validate`, `scan`, `diff` and `template` had **no
/// help text at all** — including `--format` on the two commands that make evnx
/// usable in CI, which never named `json`, `sarif` or `github`.
///
/// The prose already existed, accurately, in the guides on evnx.dev. It just
/// was not in the binary, so `evnx validate --help` was less useful than a web
/// search. This keeps it there.
#[test]
fn f16_every_flag_has_help_text() {
    let commands: &[&[&str]] = &[
        &["validate"],
        &["scan"],
        &["diff"],
        &["sync"],
        &["convert"],
        &["template"],
        &["init"],
        &["add"],
        &["doctor"],
        &["backup"],
        &["restore"],
        &["migrate"],
        &["spec", "init"],
        &["completions"],
    ];

    // Global flags are described once on the root command.
    const GLOBAL: &[&str] = &["--no-color", "--help", "--version", "--verbose", "--quiet"];

    let mut undocumented: Vec<String> = Vec::new();

    for args in commands {
        let assert = cargo_bin_cmd!("evnx").args(*args).arg("--help").assert();
        let help = String::from_utf8_lossy(&assert.get_output().stdout).to_string();
        let lines: Vec<&str> = help.lines().collect();

        for (i, line) in lines.iter().enumerate() {
            let trimmed = line.trim_start();
            let Some(flag) = trimmed
                .split_whitespace()
                .find(|w| w.starts_with("--") && w.len() > 2)
            else {
                continue;
            };
            if !trimmed.starts_with('-') {
                continue;
            }
            let flag = flag.trim_end_matches(',');
            if GLOBAL.contains(&flag) {
                continue;
            }

            // The description is the next non-blank line. If that is another
            // flag, this one has none.
            let next = lines[i + 1..]
                .iter()
                .find(|l| !l.trim().is_empty())
                .copied()
                .unwrap_or("");
            if next.trim_start().starts_with('-') && next.trim_start().contains("--") {
                undocumented.push(format!("{} {}", args.join(" "), flag));
            }
        }
    }

    assert!(
        undocumented.is_empty(),
        "flags with no help text:\n  {}",
        undocumented.join("\n  ")
    );
}

/// `--format` is the flag that makes evnx usable in CI, and neither `validate`
/// nor `scan` named its values.
#[test]
fn f16_format_names_the_formats_it_accepts() {
    for (command, expected) in [
        ("validate", vec!["json", "github-actions"]),
        ("scan", vec!["json", "sarif", "github"]),
    ] {
        let assert = cargo_bin_cmd!("evnx").args([command, "--help"]).assert();
        let help = String::from_utf8_lossy(&assert.get_output().stdout).to_string();
        for value in expected {
            assert!(
                help.contains(value),
                "`evnx {command} --help` never mentions `{value}`"
            );
        }
    }
}
