//! Regressions found by the DevRel review of 2026-09-24.
//!
//! Finding ids (`F1`…`F22`) are the review's, kept so a failure here points at
//! the write-up in `evnx-devrel-review/`.
//!
//! # Why these live together rather than in each command's file
//!
//! The review's central finding is not about any one command:
//!
//! > Every file evnx generates or repairs must pass every other evnx command.
//!
//! Three separate bugs violated it — `init` wrote a `.env.example` that a manual
//! append silently destroyed, `init --with postgresql` wrote a `DATABASE_URL`
//! that `validate --validate-formats` rejected, and `validate --fix` wrote a
//! `SECRET_KEY` that `scan` flagged. Each looked local. Together they meant a
//! user following evnx's own advice could not reach a green state.
//!
//! A test that spans commands has to live somewhere that belongs to none of
//! them.

use assert_cmd::cargo::cargo_bin_cmd;
use std::fs;
use tempfile::TempDir;

/// `init` needs a git repo to make its `.gitignore` judgements.
fn project() -> TempDir {
    let dir = TempDir::new().unwrap();
    std::process::Command::new("git")
        .args(["init", "-q"])
        .current_dir(dir.path())
        .status()
        .expect("git init");
    dir
}

// ── F20 — the file init writes must survive being appended to ───────────────

/// ⚠️ `init` wrote `.env.example` with **no trailing newline**, so the next line
/// appended to it fused onto the final comment:
///
/// ```text
/// # Generated by evnx v0.5.0 on 2026-09-24 02:08APPENDED_VAR=x
/// ```
///
/// dotenv reads that as a comment, so the variable silently disappears.
///
/// `evnx add` was immune — its writer trims and re-adds the newline — which is
/// why the bug survived: evnx's own documented next step hid it, and only a hand
/// edit or another tool was affected.
#[test]
fn f20_init_writes_a_file_that_can_be_appended_to() {
    let dir = project();

    cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["init", "--yes", "--with", "postgresql"])
        .assert()
        .success();

    let example = dir.path().join(".env.example");
    let body = fs::read_to_string(&example).unwrap();
    assert!(
        body.ends_with('\n'),
        ".env.example must end with a newline; last 60 bytes: {:?}",
        &body[body.len().saturating_sub(60)..]
    );

    // The property that actually matters: an append is a separate line.
    fs::write(&example, format!("{body}APPENDED_VAR=x\n")).unwrap();
    let after = fs::read_to_string(&example).unwrap();
    assert!(
        after.lines().any(|l| l.trim() == "APPENDED_VAR=x"),
        "the appended variable was swallowed:\n{after}"
    );
}

// ── F21 — a repair that succeeds must not report failure ────────────────────

/// ⚠️ `validate --fix` counted the issues it found on entry and never recounted,
/// so it repaired everything and then exited 1 — reporting the problems it had
/// just removed. `evnx validate --fix && deploy` never reached `deploy`, while
/// the next plain `validate` exited 0.
///
/// ⚠️ The fixture changed on 2026-09-24. It used a **missing** variable, which
/// `--fix` can only fill with `your_value_here` — and once N1 taught `validate`
/// to recognise its own `your_*` placeholders, that correctly became a finding.
/// The old fixture therefore asserted that a config holding an unfilled
/// placeholder was valid. The property F21 guards is the *recount*, so the
/// fixture now uses repairs that genuinely complete.
#[test]
fn f21_validate_fix_exits_0_when_it_fixed_everything() {
    let dir = TempDir::new().unwrap();
    fs::write(
        dir.path().join(".env"),
        "SECRET_KEY=CHANGE_ME\nDEBUG=True\n",
    )
    .unwrap();
    fs::write(dir.path().join(".env.example"), "SECRET_KEY=\nDEBUG=\n").unwrap();

    cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["validate", "--fix"])
        .assert()
        .code(0);

    // A repair that can only insert a placeholder is **not** a completed fix,
    // and must not report one. `--fix` adds the key, which is useful; the value
    // is still missing, which is the user's to supply.
    let dir3 = TempDir::new().unwrap();
    fs::write(dir3.path().join(".env"), "A=1\n").unwrap();
    fs::write(dir3.path().join(".env.example"), "A=\nB=\n").unwrap();
    let out = cargo_bin_cmd!("evnx")
        .current_dir(dir3.path())
        .args(["validate", "--fix", "--no-color"])
        .output()
        .unwrap();
    assert_eq!(
        out.status.code(),
        Some(1),
        "a variable left holding `your_value_here` is not valid config"
    );
    let text = String::from_utf8_lossy(&out.stdout);
    assert!(
        text.contains("evnx cannot invent this value"),
        "the report must not read as a contradiction — \
         `B → your_value_here` above `B looks like a placeholder`:\n{text}"
    );

    // And the complement: a problem `--fix` cannot repair must still be 1, or
    // the guard above would have been satisfiable by never failing.
    let dir2 = TempDir::new().unwrap();
    fs::write(dir2.path().join(".env"), "A=1\n").unwrap();
    fs::write(dir2.path().join(".env.example"), "A=\nB=\nC=\n").unwrap();
    fs::write(
        dir2.path().join(".evnx.toml"),
        "[vars]\nC = { format = \"port\" }\n",
    )
    .unwrap();
    let assert = cargo_bin_cmd!("evnx")
        .current_dir(dir2.path())
        .args(["validate"])
        .assert();
    let code = assert.get_output().status.code().unwrap();
    assert!(code == 1, "unfixed problems must still exit 1, got {code}");
}

// ── completions — an error is 2, in every command ───────────────────────────

/// ⚠️ `completions` called `process::exit(1)` directly, bypassing the
/// centralised mapping `main` gained in v0.5.0. So it was the one command that
/// answered an unusable argument with 1 — the code every other command reserves
/// for a real finding.
#[test]
fn completions_rejects_an_unknown_shell_with_2() {
    let assert = cargo_bin_cmd!("evnx")
        .args(["completions", "tcsh"])
        .assert()
        .code(2);

    let stderr = String::from_utf8_lossy(&assert.get_output().stderr).to_string();
    assert!(stderr.contains("No verdict"), "{stderr}");
    assert!(
        stderr.contains("bash"),
        "the error should name the valid shells: {stderr}"
    );
}

#[test]
fn completions_still_generates_for_a_known_shell() {
    for shell in ["bash", "zsh", "fish", "powershell"] {
        let assert = cargo_bin_cmd!("evnx")
            .args(["completions", shell])
            .assert()
            .code(0);
        assert!(
            !assert.get_output().stdout.is_empty(),
            "{shell} produced no completion script"
        );
    }
}

// ── F1/F2 — evnx must not reject the files evnx writes ──────────────────────

/// ⚠️ `--validate-formats` used `^https?://…`, so every `postgresql://`,
/// `redis://` and `amqp://` value was *"not a valid URL"* — including the
/// `DATABASE_URL` that `evnx init --with postgresql` had just written.
///
/// This is the review's structural finding in its clearest form: a tool that
/// generates a file its own validator rejects sends the user in a circle.
#[test]
fn f2_what_init_writes_passes_validate() {
    let dir = project();

    cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["init", "--yes", "--with", "postgresql,redis"])
        .assert()
        .success();

    let assert = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["validate", "--validate-formats", "--exit-zero"])
        .assert();
    let out = String::from_utf8_lossy(&assert.get_output().stdout).to_string();

    assert!(
        !out.contains("valid URL"),
        "evnx rejected a URL it wrote itself:\n{out}"
    );
}

/// The complement: a value that genuinely is not a URL must still be reported,
/// or the fix above would have been "accept everything".
#[test]
fn f1_a_real_non_url_is_still_reported() {
    let dir = TempDir::new().unwrap();
    fs::write(dir.path().join(".env"), "API_URL=not-a-url\n").unwrap();
    fs::write(dir.path().join(".env.example"), "API_URL=\n").unwrap();

    let assert = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["validate", "--validate-formats", "--exit-zero"])
        .assert();
    let out = String::from_utf8_lossy(&assert.get_output().stdout).to_string();

    assert!(out.contains("valid URL"), "expected a complaint:\n{out}");
}

// ── F3/F4 — doctor and the core parser must agree ───────────────────────────

/// ⚠️ `doctor` carries its own line-syntax regex, separate from `core::Parser`.
/// It omitted the optional `export` prefix, so `export FOO=bar` — which the
/// parser documents as supported and strips at `parser.rs:385` — was reported
/// as *"invalid syntax"* while `evnx validate` on the same file found zero
/// errors.
///
/// The duplication cannot simply be deleted: the parser stops at its first
/// error and `doctor` must report every bad line. So this test is what keeps
/// the two honest — it runs both over the same corpus and requires the same
/// verdict.
#[test]
fn doctor_agrees_with_the_parser_about_what_is_valid() {
    use evnx::core::Parser;

    // (line, is it valid?)
    let corpus = [
        ("KEY=value", true),
        ("export KEY=value", true),
        ("export   KEY=value", true),
        ("# a comment", true),
        ("   # indented comment", true),
        ("", true),
        ("   ", true),
        ("KEY=", true),
        ("  KEY  =  value", true),
        ("_UNDERSCORE_START=1", true),
        ("not-a-line", false),
        ("KEY value", false),
    ];

    let parser = Parser::default();

    for (line, expected_valid) in corpus {
        let dir = TempDir::new().unwrap();
        fs::write(dir.path().join(".gitignore"), ".env*\n").unwrap();
        fs::write(dir.path().join(".env"), format!("{line}\n")).unwrap();

        let assert = cargo_bin_cmd!("evnx")
            .current_dir(dir.path())
            .args(["doctor"])
            .assert();
        let out = String::from_utf8_lossy(&assert.get_output().stdout).to_string();
        let doctor_ok = !out.contains("invalid syntax");

        let parser_ok = parser.parse_content(&format!("{line}\n")).is_ok();

        assert_eq!(
            doctor_ok,
            parser_ok,
            "doctor and the parser disagree about {line:?} — doctor says {}, parser says {}",
            if doctor_ok { "valid" } else { "invalid" },
            if parser_ok { "valid" } else { "invalid" },
        );
        assert_eq!(
            doctor_ok,
            expected_valid,
            "{line:?} should be {}",
            if expected_valid { "valid" } else { "invalid" }
        );
    }
}

/// ⚠️ `validate_env_syntax` returned on the first bad line, so a file with three
/// problems took three `doctor` runs to diagnose.
#[test]
fn f4_doctor_reports_every_bad_line_not_just_the_first() {
    let dir = TempDir::new().unwrap();
    fs::write(dir.path().join(".gitignore"), ".env*\n").unwrap();
    fs::write(
        dir.path().join(".env"),
        "GOOD=1\n!!bad one\nALSO_GOOD=2\n@@bad two\n# fine\n%%bad three\n",
    )
    .unwrap();

    let assert = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["doctor"])
        .assert();
    let out = String::from_utf8_lossy(&assert.get_output().stdout).to_string();

    for line in ["Line 2", "Line 4", "Line 6"] {
        assert!(out.contains(line), "{line} was not reported:\n{out}");
    }
}

// ── F6 — the same input must produce the same output ────────────────────────

/// ⚠️ `check_missing_variables` and `check_extra_variables` built two
/// `HashSet`s and reported `difference()`. Rust seeds its hasher randomly per
/// process, so five consecutive runs over one file gave five orderings.
///
/// That makes output undiffable, defeats any golden file covering more than one
/// finding, and makes a reader ask what changed when nothing did.
///
/// ⚠️ The existing golden fixtures could not catch this: none has more than one
/// missing variable, and one item cannot be out of order. This uses five.
#[test]
fn f6_validate_reports_findings_in_a_stable_order() {
    let dir = TempDir::new().unwrap();
    fs::write(dir.path().join(".env.example"), "A=\nB=\nC=\nD=\nE=\n").unwrap();
    fs::write(dir.path().join(".env"), "A=1\n").unwrap();

    let order = |_| -> String {
        let assert = cargo_bin_cmd!("evnx")
            .current_dir(dir.path())
            .args(["validate", "--format", "json", "--exit-zero"])
            .assert();
        let v: serde_json::Value =
            serde_json::from_slice(&assert.get_output().stdout).expect("json");
        v["issues"]
            .as_array()
            .unwrap()
            .iter()
            .map(|i| i["variable"].as_str().unwrap_or("?").to_string())
            .collect::<Vec<_>>()
            .join(",")
    };

    let first = order(0);
    for run in 1..8 {
        assert_eq!(
            order(run),
            first,
            "run {run} reported a different order; the first was {first}"
        );
    }

    // And it is the order of `.env.example`, which is the file the reader has
    // open — not merely *an* order.
    assert_eq!(first, "B,C,D,E");
}

/// `sync` writes this order into `.env.example`, so a random one meant two
/// developers syncing the same `.env` produced two different files.
#[test]
fn f6_sync_writes_variables_in_the_order_they_appear() {
    let dir = TempDir::new().unwrap();
    fs::write(
        dir.path().join(".env"),
        "ZULU=1\nYANKEE=2\nXRAY=3\nWHISKEY=4\n",
    )
    .unwrap();

    let mut seen = std::collections::HashSet::new();
    for _ in 0..5 {
        let _ = fs::remove_file(dir.path().join(".env.example"));
        cargo_bin_cmd!("evnx")
            .current_dir(dir.path())
            .args(["sync", "--direction", "forward", "--placeholder"])
            .assert()
            .success();
        let body = fs::read_to_string(dir.path().join(".env.example")).unwrap();
        let order: Vec<&str> = body
            .lines()
            .filter_map(|l| l.split('=').next())
            .filter(|k| !k.trim().is_empty() && !k.starts_with('#'))
            .collect();
        seen.insert(order.join(","));
    }

    assert_eq!(seen.len(), 1, "sync wrote more than one ordering: {seen:?}");
    assert_eq!(
        seen.into_iter().next().unwrap(),
        "ZULU,YANKEE,XRAY,WHISKEY",
        "the order should be the one in .env"
    );
}

// ── F5 — a key written twice must not vanish in silence ─────────────────────

/// ⚠️ The parser builds an `IndexMap`, and `insert` overwrites — so
/// `API_KEY=first` followed by `API_KEY=second` silently became `second` and
/// nothing reported it. Last-wins is kept, because that is what dotenv
/// implementations do; the silence is what changed.
#[test]
fn f5_duplicate_keys_are_reported() {
    let dir = TempDir::new().unwrap();
    fs::write(
        dir.path().join(".env"),
        "API_KEY=first\nOTHER=x\nAPI_KEY=second\nexport OTHER=y\n",
    )
    .unwrap();
    fs::write(dir.path().join(".env.example"), "API_KEY=\nOTHER=\n").unwrap();

    let assert = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["validate", "--exit-zero"])
        .assert();
    let out = String::from_utf8_lossy(&assert.get_output().stdout).to_string();

    assert!(out.contains("API_KEY is assigned 2 times"), "{out}");
    assert!(
        out.contains("lines 1, 3"),
        "the report should name where: {out}"
    );
    // `export OTHER=y` is the same variable as `OTHER=x`.
    assert!(out.contains("OTHER is assigned 2 times"), "{out}");

    // Parsing is unchanged: the last assignment still wins.
    let converted = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["convert", "--to", "json"])
        .assert()
        .success();
    let v: serde_json::Value = serde_json::from_slice(&converted.get_output().stdout).unwrap();
    assert_eq!(v["API_KEY"], "second");
    assert_eq!(v["OTHER"], "y");
}

#[test]
fn f5_a_file_without_duplicates_is_silent() {
    let dir = TempDir::new().unwrap();
    fs::write(dir.path().join(".env"), "A=1\nB=2\n").unwrap();
    fs::write(dir.path().join(".env.example"), "A=\nB=\n").unwrap();

    let assert = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["validate"])
        .assert();
    let out = String::from_utf8_lossy(&assert.get_output().stdout).to_string();
    assert!(!out.contains("assigned"), "false positive:\n{out}");
}

// ── F8 — SARIF that GitHub can actually track ───────────────────────────────

/// ⚠️ The `ruleId` was the whole display name, so the key-name heuristic
/// produced `secret/sensitive-config-key:-acme_internal_token` — **the variable
/// name inside the rule id**. Every new variable was a new rule to GitHub, so
/// the rules list grew without bound, a dismissed alert never stayed dismissed,
/// and two runs of the same scan shared no rules at all.
///
/// There was also no `rules[]` (GitHub shows a bare id with no help link) and no
/// fingerprints (alerts are tracked by line number, so inserting a line above a
/// secret closes one alert and opens another).
#[test]
fn f8_sarif_rule_ids_identify_the_kind_not_the_instance() {
    let dir = TempDir::new().unwrap();
    fs::write(
        dir.path().join(".env"),
        "AWS_ACCESS_KEY_ID=AKIA4OZRMFJ3VREALKEY\n\
         ACME_INTERNAL_TOKEN=a-long-configuration-value-here\n\
         OTHER_SECRET_THING=another-long-configuration-value\n",
    )
    .unwrap();

    let assert = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["scan", ".env", "--format", "sarif", "--exit-zero"])
        .assert()
        .code(0);
    let doc: serde_json::Value = serde_json::from_slice(&assert.get_output().stdout).unwrap();
    let run = &doc["runs"][0];

    let rule_ids: Vec<&str> = run["tool"]["driver"]["rules"]
        .as_array()
        .expect("rules[] must exist — GitHub has no rule metadata without it")
        .iter()
        .map(|r| r["id"].as_str().unwrap())
        .collect();

    for id in &rule_ids {
        assert!(
            !id.contains("acme") && !id.contains("other_secret"),
            "a variable name leaked into a rule id: {id}"
        );
    }

    // Two findings of the same kind share one rule.
    let results = run["results"].as_array().unwrap();
    assert_eq!(results.len(), 3, "expected three findings");
    assert!(
        rule_ids.len() < results.len(),
        "three findings produced {} rules — ids are still per-instance: {rule_ids:?}",
        rule_ids.len()
    );

    // Every rule carries a help link.
    for rule in run["tool"]["driver"]["rules"].as_array().unwrap() {
        assert!(rule["helpUri"].is_string(), "rule without helpUri: {rule}");
    }

    // Every result carries a fingerprint, and they are distinct.
    let prints: Vec<&str> = results
        .iter()
        .map(|r| {
            r["partialFingerprints"]["evnxSecretV1"]
                .as_str()
                .expect("every result needs a fingerprint")
        })
        .collect();
    let unique: std::collections::HashSet<&&str> = prints.iter().collect();
    assert_eq!(
        unique.len(),
        prints.len(),
        "fingerprints collided: {prints:?}"
    );
}

// ── F11 — a missing required argument is not a licence to guess ─────────────

/// ⚠️ `select_destination` ended `.interact().unwrap_or(0)`. With no terminal —
/// every CI runner — it **silently selected the first destination in the list**,
/// so `evnx migrate --dry-run` printed a plan for somewhere the user had never
/// chosen and exited 0.
#[test]
fn f11_migrate_without_a_destination_refuses_rather_than_guessing() {
    let dir = TempDir::new().unwrap();
    fs::write(dir.path().join(".env"), "A=1\n").unwrap();

    let assert = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["migrate", "--dry-run"])
        .assert()
        .code(2);
    let stderr = String::from_utf8_lossy(&assert.get_output().stderr).to_string();
    assert!(stderr.contains("--to is required"), "{stderr}");
    assert!(
        stderr.contains("github-actions"),
        "the error should list what is available: {stderr}"
    );

    // Naming one still works — with its identifier. ⚠️ `--repo` became required
    // under --dry-run in the second review pass, because it is printed into the
    // command evnx tells the user to run; this test used to omit it.
    cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args([
            "migrate",
            "--to",
            "github-actions",
            "--repo",
            "o/r",
            "--dry-run",
        ])
        .assert()
        .code(0);
}

// ── F19 — --detect already implies --yes ────────────────────────────────────

#[test]
fn f19_detect_and_yes_are_not_in_conflict() {
    let dir = project();
    fs::write(
        dir.path().join("package.json"),
        r#"{"dependencies":{"next":"14"}}"#,
    )
    .unwrap();

    cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["init", "--detect", "--yes"])
        .assert()
        .code(0);

    assert!(dir.path().join(".env.example").exists());
}

// ── F16 — a flag with no description is a flag nobody can use ───────────────

/// ⚠️ Fourteen flags across `validate`, `scan`, `diff` and `template` had **no
/// help text at all** — including `--format` on the two commands that make evnx
/// usable in CI, which never named `json`, `sarif` or `github`.
///
/// The prose already existed, accurately, in the guides on evnx.dev. It just
/// was not in the binary, so `evnx validate --help` was less useful than a web
/// search. This keeps it there.
#[test]
fn f16_every_flag_has_help_text() {
    let commands: &[&[&str]] = &[
        &["validate"],
        &["scan"],
        &["diff"],
        &["sync"],
        &["convert"],
        &["template"],
        &["init"],
        &["add"],
        &["doctor"],
        &["backup"],
        &["restore"],
        &["migrate"],
        &["spec", "init"],
        &["completions"],
    ];

    // Global flags are described once on the root command.
    const GLOBAL: &[&str] = &["--no-color", "--help", "--version", "--verbose", "--quiet"];

    let mut undocumented: Vec<String> = Vec::new();

    for args in commands {
        let assert = cargo_bin_cmd!("evnx").args(*args).arg("--help").assert();
        let help = String::from_utf8_lossy(&assert.get_output().stdout).to_string();

        // ⚠️ Stop at the end of `Options:`. Anything below it is `after_help`,
        // which for `convert` holds shell examples whose continuation lines
        // *begin* with a flag:
        //
        // ```text
        //   evnx convert \
        //     --to kubernetes \
        //     --include "PROD_*" \
        // ```
        //
        // Scanning those, this test read `--to` as a flag declared with no
        // description and reported four documented flags as undocumented
        // (2026-09-24). The bug was in the test, not the binary.
        let options = help.rsplit("Options:").next().unwrap_or(&help);
        let options = match options.find("\nExamples:") {
            Some(end) => &options[..end],
            None => options,
        };
        let lines: Vec<&str> = options.lines().collect();

        for (i, line) in lines.iter().enumerate() {
            let trimmed = line.trim_start();
            let Some(flag) = trimmed
                .split_whitespace()
                .find(|w| w.starts_with("--") && w.len() > 2)
            else {
                continue;
            };
            if !trimmed.starts_with('-') {
                continue;
            }
            let flag = flag.trim_end_matches(',');
            if GLOBAL.contains(&flag) {
                continue;
            }

            // The description is the next non-blank line. If that is another
            // flag, this one has none.
            let next = lines[i + 1..]
                .iter()
                .find(|l| !l.trim().is_empty())
                .copied()
                .unwrap_or("");
            if next.trim_start().starts_with('-') && next.trim_start().contains("--") {
                undocumented.push(format!("{} {}", args.join(" "), flag));
            }
        }
    }

    assert!(
        undocumented.is_empty(),
        "flags with no help text:\n  {}",
        undocumented.join("\n  ")
    );
}

/// `--format` is the flag that makes evnx usable in CI, and neither `validate`
/// nor `scan` named its values.
#[test]
fn f16_format_names_the_formats_it_accepts() {
    for (command, expected) in [
        ("validate", vec!["json", "github-actions"]),
        ("scan", vec!["json", "sarif", "github"]),
    ] {
        let assert = cargo_bin_cmd!("evnx").args([command, "--help"]).assert();
        let help = String::from_utf8_lossy(&assert.get_output().stdout).to_string();
        for value in expected {
            assert!(
                help.contains(value),
                "`evnx {command} --help` never mentions `{value}`"
            );
        }
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Second pass — from the fix review of 2026-09-24 (fix_version_1.md)
// ═══════════════════════════════════════════════════════════════════════════

/// ⚠️ **A secret was printed that existed nowhere.**
///
/// `SECRET_KEY=CHANGE_ME` trips both the placeholder check and the weak-secret
/// check. Each queued its own fix and each called `generate_secure_secret()`, so
/// two different 256-bit values were generated, **both printed in the report**,
/// and only the second reached the file.
///
/// Someone copying the first into a dashboard or a password manager held a
/// credential that appeared nowhere in their `.env`, and would debug an
/// authentication failure with no visible cause. It also reported "2 fixed" for
/// one repaired variable.
#[test]
fn validate_fix_repairs_each_variable_once() {
    let dir = TempDir::new().unwrap();
    fs::write(dir.path().join(".env.example"), "SECRET_KEY=\n").unwrap();
    fs::write(dir.path().join(".env"), "SECRET_KEY=CHANGE_ME\n").unwrap();

    let assert = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["validate", "--fix"])
        .assert()
        .code(0);
    let out = String::from_utf8_lossy(&assert.get_output().stdout).to_string();

    let reported: Vec<&str> = out.lines().filter(|l| l.contains("SECRET_KEY:")).collect();
    assert_eq!(
        reported.len(),
        1,
        "one variable must produce one fix, got {}:\n{out}",
        reported.len()
    );

    // Every value printed must be the value that landed.
    let landed = fs::read_to_string(dir.path().join(".env")).unwrap();
    let value = landed
        .trim()
        .strip_prefix("SECRET_KEY=")
        .expect("SECRET_KEY should be set");
    assert!(
        reported[0].contains(value),
        "the report printed a secret that is not in the file.\n  reported: {}\n  landed:   {value}",
        reported[0]
    );
}

/// ⚠️ F9, as actually filed — against `validate`, not `scan`.
///
/// Each finding emitted **two** annotations (message, then suggestion), both
/// anchored to `line=1`. GitHub caps annotations at 10 per step, so five missing
/// variables exhausted the budget and the rest were dropped — on the command
/// whose job is to list what is missing.
#[test]
fn f9_validate_github_format_is_one_annotation_per_finding() {
    let dir = TempDir::new().unwrap();
    fs::write(dir.path().join(".env"), "A=1\n").unwrap();
    fs::write(
        dir.path().join(".env.example"),
        "A=\nSENTRY_DSN=\nOPENAI_API_KEY=\nSTRIPE_KEY=\n",
    )
    .unwrap();

    let assert = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["validate", "--format", "github", "--exit-zero"])
        .assert()
        .code(0);
    let out = String::from_utf8_lossy(&assert.get_output().stdout).to_string();
    let annotations: Vec<&str> = out.lines().filter(|l| l.starts_with("::")).collect();

    assert_eq!(
        annotations.len(),
        3,
        "three missing variables should be three annotations, got {}:\n{out}",
        annotations.len()
    );
    // The suggestion travels inside the message rather than as its own line.
    assert!(
        annotations.iter().all(|a| a.contains("%0ASuggestion:")),
        "the suggestion should be folded into the message:\n{out}"
    );
}

/// An issue about a line that exists should point at that line, not at line 1.
#[test]
fn f9_annotations_point_at_the_real_line() {
    let dir = TempDir::new().unwrap();
    fs::write(
        dir.path().join(".env"),
        "# comment\n# another\nA=1\nAPI_KEY=changeme\n",
    )
    .unwrap();
    fs::write(dir.path().join(".env.example"), "A=\nAPI_KEY=\n").unwrap();

    let assert = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["validate", "--format", "github", "--exit-zero"])
        .assert()
        .code(0);
    let out = String::from_utf8_lossy(&assert.get_output().stdout).to_string();

    assert!(
        out.contains("line=4"),
        "API_KEY is on line 4 of .env:\n{out}"
    );
}

/// ⚠️ F11, as actually filed. `--dry-run` printed
/// `heroku config --app <--heroku-app not set>` — an internal placeholder inside
/// the command it tells the user to run — and exited 0.
#[test]
fn f11_dry_run_needs_the_identifier_it_would_print() {
    let dir = TempDir::new().unwrap();
    fs::write(dir.path().join(".env"), "A=1\n").unwrap();

    let assert = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["migrate", "--to", "heroku", "--dry-run"])
        .assert()
        .code(2);
    let stderr = String::from_utf8_lossy(&assert.get_output().stderr).to_string();
    assert!(stderr.contains("--heroku-app"), "{stderr}");

    // Given the name, the preview works.
    let ok = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args([
            "migrate",
            "--to",
            "heroku",
            "--heroku-app",
            "my-app",
            "--dry-run",
        ])
        .assert()
        .code(0);
    let out = String::from_utf8_lossy(&ok.get_output().stdout).to_string();
    assert!(out.contains("my-app"), "{out}");
    assert!(
        !out.contains("not set"),
        "a placeholder leaked into the preview:\n{out}"
    );

    // ⚠️ A *credential* is different: --dry-run uploads nothing, so it must
    // still work without one. This is what PR #51 fixed and must not regress.
    cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args([
            "migrate",
            "--to",
            "github-actions",
            "--repo",
            "o/r",
            "--dry-run",
        ])
        .assert()
        .code(0);
}

/// ⚠️ F2's remaining leg. `init` wrote `your_next_public_api_url_value` into a
/// URL-typed key, which `--validate-formats` then rejected — three of the
/// stack's four URL keys had URL-shaped examples and one did not.
#[test]
fn f2_init_writes_url_shaped_values_for_url_keys() {
    let dir = project();

    cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["init", "--yes", "--with", "nextjs,postgresql"])
        .assert()
        .success();

    let example = fs::read_to_string(dir.path().join(".env.example")).unwrap();
    for line in example.lines() {
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        let key = key.trim();
        if key.starts_with('#') {
            continue;
        }
        if key.ends_with("_URL") || key.ends_with("_URI") || key.ends_with("_ENDPOINT") {
            assert!(
                value.contains("://"),
                "{key} is URL-typed but its example is {value:?}"
            );
        }
    }
}

// ── F18 — a finding must not claim more than the detector checked ───────────

/// ⚠️ `scan` printed "matches a live key format, not a placeholder" under
/// **every** high-confidence finding, including ones reached purely by the
/// variable's *name*. So `NEXTAUTH_SECRET=dev-not-a-real-secret` was reported
/// as a value matching a live key format — about a value that says it is not
/// one, and that no detector had read.
///
/// The claim is load-bearing: it is what tells a user to drop everything and
/// rotate. Attaching it to a name match trains people to ignore it.
#[test]
fn f18_name_based_findings_do_not_claim_the_value_matched() {
    let dir = TempDir::new().unwrap();
    fs::write(
        dir.path().join(".env"),
        "NEXTAUTH_SECRET=dev-not-a-real-secret\n\
         GITHUB_TOKEN=ghp_A1b2C3d4E5f6G7h8I9j0K1l2M3n4O5p6Q7r8\n",
    )
    .unwrap();

    let out = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .arg("scan")
        .arg("--no-color")
        .output()
        .unwrap();
    let text = String::from_utf8_lossy(&out.stdout);

    // Both are still findings — this is about wording, not suppression.
    assert!(text.contains("NEXTAUTH_SECRET"), "{text}");
    assert!(text.contains("GitHub Token"), "{text}");

    // The real token earned the claim.
    assert!(
        text.contains("matches a live key format"),
        "a genuine ghp_ match must still say so:\n{text}"
    );

    // The name match did not. Locate the line that follows each finding.
    let lines: Vec<&str> = text.lines().collect();
    let idx = lines
        .iter()
        .position(|l| l.contains("NEXTAUTH_SECRET") && l.contains(".env:"))
        .unwrap_or_else(|| panic!("no location line for NEXTAUTH_SECRET:\n{text}"));
    let note = lines[idx + 1];
    assert!(
        !note.contains("matches a live key format"),
        "a name-based finding must not claim the value matched a format:\n  {note}"
    );
    assert!(
        note.contains("flagged by variable name"),
        "it must say what actually happened instead:\n  {note}"
    );
}

// ── F7 — backup and restore must accept the same password, both ways ────────

/// ⚠️ `backup` ignored `EVNX_PASSWORD` while `restore` honoured it, so the two
/// halves of one pipeline disagreed about how a passphrase arrives. The
/// consequence was concrete: a scheduled backup had no way to supply one except
/// writing it to disk, while the restore it fed needed no file at all.
#[test]
fn f7_evnx_password_drives_a_backup_with_no_file_on_disk() {
    let dir = TempDir::new().unwrap();
    fs::write(dir.path().join(".env"), "API_KEY=sk-live-abc123\n").unwrap();

    cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .env("EVNX_PASSWORD", "correct-horse-battery-staple")
        .args(["backup", "--output", "a.backup"])
        .assert()
        .success();

    cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .env("EVNX_PASSWORD", "correct-horse-battery-staple")
        .args(["restore", "a.backup", "--output", "out.env"])
        .assert()
        .success();

    assert_eq!(
        fs::read_to_string(dir.path().join("out.env")).unwrap(),
        "API_KEY=sk-live-abc123\n"
    );
}

/// ⚠️ The deeper half of F7, and the reason the flag aliases could not be added
/// on their own. `backup --key-file` Base64-encodes a **binary** key file before
/// Argon2id; `restore --password-file` read the same file with `read_to_string`
/// and stripped a trailing newline. So one file produced two different
/// passwords, and the only symptom was a backup that would not open.
///
/// Aliasing the two spellings without unifying the reader would have made that
/// trap easier to reach, not harder — the flag names would finally match while
/// the behaviour still did not.
#[test]
fn f7_one_key_file_round_trips_under_either_flag_spelling() {
    let dir = TempDir::new().unwrap();
    fs::write(dir.path().join(".env"), "API_KEY=sk-live-abc123\n").unwrap();

    // Bytes that are deliberately not valid UTF-8, the case `read_to_string`
    // could not read at all.
    fs::write(
        dir.path().join("binary.key"),
        [0xf0, 0x9f, 0x00, 0xff, 0xfe],
    )
    .unwrap();

    // Crossed on purpose: backup gets restore's spelling and vice versa.
    cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args([
            "backup",
            "--password-file",
            "binary.key",
            "--output",
            "b.backup",
        ])
        .assert()
        .success();

    cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args([
            "restore",
            "b.backup",
            "--key-file",
            "binary.key",
            "--output",
            "out.env",
        ])
        .assert()
        .success();

    assert_eq!(
        fs::read_to_string(dir.path().join("out.env")).unwrap(),
        "API_KEY=sk-live-abc123\n"
    );
}

// ── F12 — a dry run must not report that anything happened ─────────────────

/// ⚠️ `migrate --dry-run` printed `✓ 0 command(s) generated` while printing the
/// commands, then followed it with the destination's real next steps —
/// "verify secrets were set", "redeploy your project". Both halves described a
/// migration that had not occurred.
#[test]
fn f12_dry_run_does_not_claim_anything_was_done() {
    let dir = TempDir::new().unwrap();
    fs::write(
        dir.path().join(".env"),
        "API_KEY=abc\nDB_URL=postgres://u:p@h/d\nPORT=3000\n",
    )
    .unwrap();

    let out = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["migrate", "--to", "vercel", "--dry-run", "--no-color"])
        .output()
        .unwrap();
    let text = String::from_utf8_lossy(&out.stdout);

    assert!(
        text.contains("nothing was uploaded"),
        "the summary must say nothing happened:\n{text}"
    );
    assert!(
        !text.contains("were set"),
        "a dry run must not tell the user to verify secrets it never set:\n{text}"
    );
    assert!(
        !text.contains("Redeploy") && !text.contains("redeploy"),
        "nor to redeploy for a migration that did not happen:\n{text}"
    );
    assert!(
        text.contains("Re-run without --dry-run"),
        "it must say what the actual next step is:\n{text}"
    );
    // The count must reflect the three secrets, not zero.
    assert!(
        text.contains("3 secret(s) previewed"),
        "the count must match what was previewed:\n{text}"
    );
}

// ── F14 — help examples must be runnable, not rendered Markdown ─────────────

/// ⚠️ `convert`'s examples lived in a doc comment inside a ```` ```text ````
/// fence. clap prints doc comments verbatim, so the fence markers and the shell
/// line-continuation backslashes were rendered literally and the whole block
/// collapsed onto one line — the one place in the CLI where copying an example
/// could not work.
#[test]
fn f14_convert_help_examples_are_copy_pasteable() {
    let out = cargo_bin_cmd!("evnx")
        .args(["convert", "--help"])
        .output()
        .unwrap();
    let text = String::from_utf8_lossy(&out.stdout);

    assert!(
        !text.contains("```"),
        "a Markdown fence must never reach the terminal:\n{text}"
    );

    // The last "Examples:" is the `after_help` block; the earlier ones belong
    // to individual flag doc comments.
    let examples = text
        .rsplit("Examples:")
        .next()
        .expect("convert --help must carry an examples block");

    // The multi-line example must still be multi-line: a continuation backslash
    // is only correct at end of line. Mid-line means the block was collapsed.
    for line in examples.lines() {
        let line = line.trim_end();
        if let Some(pos) = line.find('\\') {
            assert_eq!(
                pos,
                line.len() - 1,
                "a continuation backslash mid-line means the block collapsed:\n  {line}"
            );
        }
    }

    assert!(
        examples.contains("  evnx convert --to json"),
        "the simplest example must appear as a runnable line:\n{examples}"
    );
}

// ── N1 — validate must recognise the placeholders evnx itself writes ────────

/// ⚠️ `evnx init` generates `your_<name>_value`. `validate`'s placeholder list
/// held `your_key_here`, `your_secret_here` and `your_token_here` — the suffix
/// is `_here`, not `_value` — so none of them matched.
///
/// The consequence was the sharpest form of "evnx must pass its own output"
/// found so far: `evnx init --with nextjs,postgresql` then the documented
/// `cp .env.example .env` produced a `DB_PASSWORD` and a `NEXTAUTH_SECRET`
/// still holding placeholders, and `evnx validate` said **nothing about
/// either**. A forgotten password reaching production is the single thing this
/// command exists to prevent.
#[test]
fn n1_what_init_generates_does_not_pass_validate_unfilled() {
    let dir = project();

    cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["init", "--yes", "--with", "nextjs,postgresql"])
        .assert()
        .success();

    // The documented next step.
    fs::copy(dir.path().join(".env.example"), dir.path().join(".env")).unwrap();

    let out = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["validate", "--no-color"])
        .output()
        .unwrap();
    let text = String::from_utf8_lossy(&out.stdout);

    assert_eq!(
        out.status.code(),
        Some(1),
        "a generated .env full of unfilled credentials must not validate clean:\n{text}"
    );
    for var in ["DB_PASSWORD", "NEXTAUTH_SECRET"] {
        assert!(
            text.contains(&format!("{var} looks like a placeholder")),
            "{var} still holds a generated placeholder and must be named as one \
             — not merely mentioned, which N2's weak-secret check would also do:\n{text}"
        );
    }

    // A placeholder too long to trip the 32-character weak-secret floor, so
    // only the placeholder rule can catch it.
    let long = TempDir::new().unwrap();
    fs::write(
        long.path().join(".env"),
        "ANALYTICS_WRITE_KEY=your_analytics_write_key_value_goes_right_here\n",
    )
    .unwrap();
    fs::write(long.path().join(".env.example"), "ANALYTICS_WRITE_KEY=\n").unwrap();
    let out = cargo_bin_cmd!("evnx")
        .current_dir(long.path())
        .args(["validate", "--no-color"])
        .output()
        .unwrap();
    let text = String::from_utf8_lossy(&out.stdout);
    assert!(
        text.contains("ANALYTICS_WRITE_KEY looks like a placeholder"),
        "a long `your_*_value` is still a placeholder:\n{text}"
    );
}

/// The complement: the broadened rule must not start calling real values
/// placeholders. `your_` is distinctive; `development` is not.
#[test]
fn n1_real_values_are_not_called_placeholders() {
    let dir = TempDir::new().unwrap();
    fs::write(
        dir.path().join(".env"),
        "ENVIRONMENT=development\nREGION=us-east-1\nTEAM=platform\n",
    )
    .unwrap();
    fs::write(
        dir.path().join(".env.example"),
        "ENVIRONMENT=\nREGION=\nTEAM=\n",
    )
    .unwrap();

    let out = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["validate", "--no-color"])
        .output()
        .unwrap();
    let text = String::from_utf8_lossy(&out.stdout);
    assert!(
        !text.contains("looks like a placeholder"),
        "ordinary values must not be flagged:\n{text}"
    );
}

// ── N2 — the weak-secret check applied to one hardcoded name ────────────────

/// ⚠️ `check_weak_secret` was `env_vars.get("SECRET_KEY")` — a single literal
/// lookup — so `JWT_SECRET=weak`, `SESSION_SECRET=123` and `DB_PASSWORD=dev`
/// all validated clean while the identically worthless `SECRET_KEY=weak` was an
/// error. `is_weak_secret_key` always accepted any key; only the call site was
/// narrow.
#[test]
fn n2_every_secret_shaped_variable_is_checked_for_weakness() {
    for name in [
        "SECRET_KEY",
        "JWT_SECRET",
        "API_SECRET",
        "SESSION_SECRET",
        "DB_PASSWORD",
        "GITHUB_TOKEN",
    ] {
        let dir = TempDir::new().unwrap();
        fs::write(dir.path().join(".env"), format!("{name}=weak\n")).unwrap();
        fs::write(dir.path().join(".env.example"), format!("{name}=\n")).unwrap();

        let out = cargo_bin_cmd!("evnx")
            .current_dir(dir.path())
            .args(["validate", "--no-color"])
            .output()
            .unwrap();
        let text = String::from_utf8_lossy(&out.stdout);
        assert!(
            text.contains("too weak or predictable"),
            "{name}=weak must be reported:\n{text}"
        );
    }
}

/// The complement, twice over: a name that merely *contains* a secret word but
/// holds a number, and a genuinely generated secret, must both stay silent.
#[test]
fn n2_does_not_flag_non_secrets_or_generated_secrets() {
    let dir = TempDir::new().unwrap();
    fs::write(
        dir.path().join(".env"),
        // 64 hex characters containing `1234` — the shape `validate --fix`
        // generates, and one it used to call weak roughly once in 500 runs.
        "SECRET_KEY_ROTATION_DAYS=30\n\
         SECRET_KEY=09c15d5e87c2b45f1234b58733f7f0d35ae4bc8a0c0c8218f31da3e012546bb0\n",
    )
    .unwrap();
    fs::write(
        dir.path().join(".env.example"),
        "SECRET_KEY_ROTATION_DAYS=\nSECRET_KEY=\n",
    )
    .unwrap();

    let out = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["validate", "--no-color"])
        .output()
        .unwrap();
    let text = String::from_utf8_lossy(&out.stdout);
    assert!(
        !text.contains("too weak"),
        "neither a rotation-period number nor a generated secret is weak:\n{text}"
    );
}

// ── #12 — a file that is absent is not a file that failed to parse ─────────

/// ⚠️ GitHub issue #12, open since March. `evnx diff` with no `.env.example`
/// reported *"Failed to parse .env.example"*, which sends you looking for a
/// syntax error in a file that does not exist. `validate` was worse: it printed
/// the OS error twice, because the error's own message interpolated the source
/// that anyhow then printed again.
#[test]
fn i12_a_missing_file_is_reported_as_missing() {
    for cmd in ["diff", "validate"] {
        let dir = TempDir::new().unwrap();
        fs::write(dir.path().join(".env"), "A=1\n").unwrap();

        let out = cargo_bin_cmd!("evnx")
            .current_dir(dir.path())
            .args([cmd, "--no-color"])
            .output()
            .unwrap();
        let err = String::from_utf8_lossy(&out.stderr);

        assert!(
            err.contains(".env.example does not exist"),
            "{cmd} must say the file is missing:\n{err}"
        );
        assert!(
            !err.contains("Failed to parse"),
            "{cmd} must not call an absent file unparseable:\n{err}"
        );
        assert!(
            err.contains("evnx sync") || err.contains("evnx init"),
            "{cmd} must say how to create it:\n{err}"
        );
        assert_eq!(
            err.matches("No such file or directory").count(),
            0,
            "the raw OS error should not surface at all now:\n{err}"
        );
    }
}

/// The complement, and the one that would otherwise be silently lost: a file
/// that really is malformed must still say so — **with the line number**.
///
/// ⚠️ `diff` printed its error with `{}` rather than anyhow's `{:#}`, so only
/// the outermost context survived: "Failed to parse .env.example", with the
/// "Invalid format at line 1: missing '=' separator" that says what to fix
/// dropped. Four of the seven error sites in `main.rs` shared the bug; the
/// other three print a downcast Backup/RestoreError, where `{}` is correct.
#[test]
fn i12_an_unparseable_file_still_names_the_line() {
    let dir = TempDir::new().unwrap();
    fs::write(dir.path().join(".env"), "A=1\n").unwrap();
    fs::write(dir.path().join(".env.example"), "this is not valid\n").unwrap();

    let out = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["diff", "--no-color"])
        .output()
        .unwrap();
    let err = String::from_utf8_lossy(&out.stderr);

    assert!(err.contains("Failed to parse"), "{err}");
    assert!(
        err.contains("line 1"),
        "the cause must survive to the terminal, not just the context:\n{err}"
    );
}

// ── #13 / F10 — migrate must not report a migration that did not happen ────

/// ⚠️ GitHub issue #13. The zero-secrets branch returned `Ok(())` before the
/// docs hint, so a migrate that moved nothing exited 0 and printed no link —
/// which is exactly the transcript in the issue. It also named the *source
/// kind* (`env-file`) rather than the file, so it could not tell "the file is
/// empty" from "I am in the wrong directory".
#[test]
fn i13_a_migration_that_moved_nothing_is_not_a_success() {
    let dir = TempDir::new().unwrap();
    fs::write(dir.path().join(".env"), "").unwrap();

    let out = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["migrate", "--to", "vercel", "--dry-run", "--no-color"])
        .output()
        .unwrap();
    let err = String::from_utf8_lossy(&out.stderr);

    assert_eq!(out.status.code(), Some(2), "stderr:\n{err}");
    assert!(
        err.contains(".env holds no variables"),
        "it must name the file, not the source kind:\n{err}"
    );
    // `print_docs_hint` writes to stderr, alongside the error it accompanies.
    assert!(
        err.contains("guides/commands/migrate"),
        "the docs link is what issue #13 is about:\n{err}"
    );
}

/// The same rule for a filter that matches nothing — which is already how
/// `evnx cloud run` behaves, so the two now agree.
#[test]
fn i13_a_filter_that_matches_nothing_is_an_error() {
    let dir = TempDir::new().unwrap();
    fs::write(dir.path().join(".env"), "A=1\nB=2\n").unwrap();

    let out = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args([
            "migrate",
            "--to",
            "vercel",
            "--include",
            "NOPE_*",
            "--dry-run",
            "--no-color",
        ])
        .output()
        .unwrap();
    let err = String::from_utf8_lossy(&out.stderr);

    assert_eq!(out.status.code(), Some(2), "stderr:\n{err}");
    assert!(err.contains("filtered out"), "{err}");
    assert!(err.contains(".env"), "it must name the file:\n{err}");
}

/// ⚠️ F10, flagged in three consecutive reviews and fixed in none.
/// `--skip-existing` and `--overwrite` are about secrets already present at the
/// destination, which only a destination evnx actually talks to can know. The
/// eight that merely print commands accepted both in silence — no warning, no
/// effect, exit 0.
#[test]
fn f10_flags_that_cannot_work_are_refused_not_ignored() {
    let dir = TempDir::new().unwrap();
    fs::write(dir.path().join(".env"), "A=1\n").unwrap();

    let out = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args([
            "migrate",
            "--to",
            "doppler",
            "--project",
            "p",
            "--dry-run",
            "--skip-existing",
            "--no-color",
        ])
        .output()
        .unwrap();
    let err = String::from_utf8_lossy(&out.stderr);
    assert_eq!(out.status.code(), Some(2), "stdout+stderr:\n{err}");
    assert!(err.contains("--skip-existing"), "{err}");
    assert!(
        err.contains("github-actions"),
        "it must say which destination does honour it:\n{err}"
    );

    // The control: the one destination that uploads still takes them, and its
    // dry run counts what it previewed rather than reporting zero.
    let out = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args([
            "migrate",
            "--to",
            "github-actions",
            "--repo",
            "o/r",
            "--dry-run",
            "--skip-existing",
            "--no-color",
        ])
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(0));
    let text = String::from_utf8_lossy(&out.stdout);
    assert!(
        text.contains("1 secret(s) previewed"),
        "the ninth destination's dry run reported 0 while previewing 1:\n{text}"
    );
}

// ── #10.4 — a writer must not produce what the reader refuses ──────────────

/// ⚠️ GitHub issue #10, item 4. `evnx add custom` took the variable name
/// straight from the prompt with no validation, so entering `NODE_VERSION=22`
/// wrote `# TODO: NODE_VERSION=22=22`. The parser has always refused such a
/// key — it was simply never asked. `evnx` could write a file `evnx` could not
/// read.
#[test]
fn i10_4_the_key_rule_is_shared_between_reader_and_writer() {
    use evnx::core::parser::is_valid_key;

    // The issue's input, and the shapes around it.
    assert!(!is_valid_key("NODE_VERSION=22"), "the reported bug");
    assert!(!is_valid_key("2FAST"), "a leading digit");
    assert!(!is_valid_key("HAS SPACE"));
    assert!(!is_valid_key("HAS-DASH"));
    assert!(!is_valid_key(""));

    assert!(is_valid_key("NODE_VERSION"));
    assert!(
        is_valid_key("_PRIVATE"),
        "POSIX allows a leading underscore"
    );
    assert!(is_valid_key("A1"));
}

/// N3 — every line of a generated `.env` starts at column 0.
#[test]
fn n3_generated_files_have_no_stray_indentation() {
    let dir = project();
    cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["init", "--yes", "--with", "postgresql"])
        .assert()
        .success();

    for name in [".env", ".env.example"] {
        let body = fs::read_to_string(dir.path().join(name)).unwrap();
        for (i, line) in body.lines().enumerate() {
            assert!(
                !line.starts_with(' '),
                "{name}:{} is indented: {line:?}",
                i + 1
            );
        }
    }
}

// ── F18, part two — the machine formats over-claimed too ───────────────────

/// ⚠️ F18 reached the terminal and stopped there. `scan --format json` returned
/// identical field sets for a value match and a name match, and
/// `--format github` still said *"matches"* and *"Rotate this credential"* for
/// a finding reached purely by name. CI is the audience most likely to automate
/// on "is this a real leak?", and it was the audience that could not tell.
#[test]
fn f18_machine_formats_distinguish_name_from_value() {
    let dir = TempDir::new().unwrap();
    fs::write(
        dir.path().join(".env"),
        "NEXTAUTH_SECRET=dev-not-a-real-secret\nAWS_KEY=AKIAIOSFODNN7EXAMPLQ\n",
    )
    .unwrap();

    let out = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["scan", "--format", "json"])
        .output()
        .unwrap();
    let json: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    let by: std::collections::HashMap<&str, &str> = json["findings"]
        .as_array()
        .unwrap()
        .iter()
        .map(|f| {
            (
                f["variable"].as_str().unwrap(),
                f["matched_by"]
                    .as_str()
                    .expect("matched_by must be present"),
            )
        })
        .collect();
    assert_eq!(by.get("NEXTAUTH_SECRET"), Some(&"name"));
    assert_eq!(by.get("AWS_KEY"), Some(&"value"));

    let out = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["scan", "--format", "github"])
        .output()
        .unwrap();
    let text = String::from_utf8_lossy(&out.stdout);
    let name_line = text
        .lines()
        .find(|l| l.contains("NEXTAUTH_SECRET"))
        .expect("an annotation for the name match");
    assert!(
        !name_line.contains("Rotate"),
        "a name match must not order a rotation:\n{name_line}"
    );
    assert!(
        name_line.contains("not checked"),
        "it must say the value went unread:\n{name_line}"
    );

    let value_line = text
        .lines()
        .find(|l| l.contains("AWS_KEY"))
        .expect("an annotation for the value match");
    assert!(
        value_line.contains("Rotate it at"),
        "a real key match must still say rotate:\n{value_line}"
    );
}

// ── --fix must repair what it can and decline what it cannot ───────────────

/// ⚠️ Surfaced by N1: once `validate` recognised `your_*_value`, `--fix`
/// started "repairing" `DB_NAME=your_db_name_value` into
/// `DB_NAME=your_value_here` — one placeholder for a **less informative** one,
/// reported as a fix, directly above the finding it did not resolve. It also
/// discarded the only hint the line carried about the variable's purpose.
///
/// evnx can invent a secret, a URL, an email and a port. It cannot invent a
/// database name, so it must not offer to.
#[test]
fn fix_declines_what_it_cannot_invent_and_says_so() {
    let dir = project();
    cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["init", "--yes", "--with", "postgresql"])
        .assert()
        .success();
    fs::copy(dir.path().join(".env.example"), dir.path().join(".env")).unwrap();

    let before = fs::read_to_string(dir.path().join(".env")).unwrap();
    assert!(before.contains("DB_NAME=your_db_name_value"), "{before}");

    let out = cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["validate", "--fix", "--no-color"])
        .output()
        .unwrap();
    let text = String::from_utf8_lossy(&out.stdout);
    let after = fs::read_to_string(dir.path().join(".env")).unwrap();

    assert!(
        after.contains("DB_NAME=your_db_name_value"),
        "a placeholder evnx cannot replace must be left intact:\n{after}"
    );
    assert!(
        !text.contains("your_value_here"),
        "swapping one placeholder for a vaguer one is not a fix:\n{text}"
    );
    assert!(
        !text.contains("DB_NAME") || !text.contains("• DB_NAME"),
        "DB_NAME must not be listed among the applied fixes:\n{text}"
    );

    // The complement: the credential in the same file *is* repaired.
    let pw = after
        .lines()
        .find(|l| l.starts_with("DB_PASSWORD="))
        .expect("DB_PASSWORD line");
    assert!(
        !pw.contains("your_"),
        "a password is something evnx can generate:\n{pw}"
    );
}

/// ⚠️ The fixer carried N2's bug as well: `.find(...)` took the first
/// weak-secret issue and then looked up `env_vars.get("SECRET_KEY")` regardless
/// of which variable it was about — so at most one was repaired per run, and
/// only if it happened to be named `SECRET_KEY`.
#[test]
fn fix_repairs_every_weak_secret_not_just_the_first() {
    let dir = TempDir::new().unwrap();
    fs::write(
        dir.path().join(".env"),
        "JWT_SECRET=weak\nSESSION_SECRET=weak\nDB_PASSWORD=weak\n",
    )
    .unwrap();
    fs::write(
        dir.path().join(".env.example"),
        "JWT_SECRET=\nSESSION_SECRET=\nDB_PASSWORD=\n",
    )
    .unwrap();

    cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["validate", "--fix", "--no-color"])
        .assert()
        .code(0);

    let after = fs::read_to_string(dir.path().join(".env")).unwrap();
    for name in ["JWT_SECRET", "SESSION_SECRET", "DB_PASSWORD"] {
        let line = after
            .lines()
            .find(|l| l.starts_with(&format!("{name}=")))
            .unwrap_or_else(|| panic!("{name} missing:\n{after}"));
        let value = line.split_once('=').unwrap().1;
        assert!(value.len() >= 32, "{name} was not regenerated: {line}");
    }
}
