//! Regressions found by the DevRel review of 2026-09-24.
//!
//! Finding ids (`F1`…`F22`) are the review's, kept so a failure here points at
//! the write-up in `evnx-devrel-review/`.
//!
//! # Why these live together rather than in each command's file
//!
//! The review's central finding is not about any one command:
//!
//! > Every file evnx generates or repairs must pass every other evnx command.
//!
//! Three separate bugs violated it — `init` wrote a `.env.example` that a manual
//! append silently destroyed, `init --with postgresql` wrote a `DATABASE_URL`
//! that `validate --validate-formats` rejected, and `validate --fix` wrote a
//! `SECRET_KEY` that `scan` flagged. Each looked local. Together they meant a
//! user following evnx's own advice could not reach a green state.
//!
//! A test that spans commands has to live somewhere that belongs to none of
//! them.

use assert_cmd::cargo::cargo_bin_cmd;
use std::fs;
use tempfile::TempDir;

/// `init` needs a git repo to make its `.gitignore` judgements.
fn project() -> TempDir {
    let dir = TempDir::new().unwrap();
    std::process::Command::new("git")
        .args(["init", "-q"])
        .current_dir(dir.path())
        .status()
        .expect("git init");
    dir
}

// ── F20 — the file init writes must survive being appended to ───────────────

/// ⚠️ `init` wrote `.env.example` with **no trailing newline**, so the next line
/// appended to it fused onto the final comment:
///
/// ```text
/// # Generated by evnx v0.5.0 on 2026-09-24 02:08APPENDED_VAR=x
/// ```
///
/// dotenv reads that as a comment, so the variable silently disappears.
///
/// `evnx add` was immune — its writer trims and re-adds the newline — which is
/// why the bug survived: evnx's own documented next step hid it, and only a hand
/// edit or another tool was affected.
#[test]
fn f20_init_writes_a_file_that_can_be_appended_to() {
    let dir = project();

    cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["init", "--yes", "--with", "postgresql"])
        .assert()
        .success();

    let example = dir.path().join(".env.example");
    let body = fs::read_to_string(&example).unwrap();
    assert!(
        body.ends_with('\n'),
        ".env.example must end with a newline; last 60 bytes: {:?}",
        &body[body.len().saturating_sub(60)..]
    );

    // The property that actually matters: an append is a separate line.
    fs::write(&example, format!("{body}APPENDED_VAR=x\n")).unwrap();
    let after = fs::read_to_string(&example).unwrap();
    assert!(
        after.lines().any(|l| l.trim() == "APPENDED_VAR=x"),
        "the appended variable was swallowed:\n{after}"
    );
}

// ── F21 — a repair that succeeds must not report failure ────────────────────

/// ⚠️ `validate --fix` counted the issues it found on entry and never recounted,
/// so it repaired everything and then exited 1 — reporting the problems it had
/// just removed. `evnx validate --fix && deploy` never reached `deploy`, while
/// the next plain `validate` exited 0.
#[test]
fn f21_validate_fix_exits_0_when_it_fixed_everything() {
    let dir = TempDir::new().unwrap();
    fs::write(dir.path().join(".env"), "A=1\n").unwrap();
    fs::write(dir.path().join(".env.example"), "A=\nB=\n").unwrap();

    cargo_bin_cmd!("evnx")
        .current_dir(dir.path())
        .args(["validate", "--fix"])
        .assert()
        .code(0);

    // And the complement: a problem `--fix` cannot repair must still be 1, or
    // the guard above would have been satisfiable by never failing.
    let dir2 = TempDir::new().unwrap();
    fs::write(dir2.path().join(".env"), "A=1\n").unwrap();
    fs::write(dir2.path().join(".env.example"), "A=\nB=\nC=\n").unwrap();
    fs::write(
        dir2.path().join(".evnx.toml"),
        "[vars]\nC = { format = \"port\" }\n",
    )
    .unwrap();
    let assert = cargo_bin_cmd!("evnx")
        .current_dir(dir2.path())
        .args(["validate"])
        .assert();
    let code = assert.get_output().status.code().unwrap();
    assert!(code == 1, "unfixed problems must still exit 1, got {code}");
}

// ── completions — an error is 2, in every command ───────────────────────────

/// ⚠️ `completions` called `process::exit(1)` directly, bypassing the
/// centralised mapping `main` gained in v0.5.0. So it was the one command that
/// answered an unusable argument with 1 — the code every other command reserves
/// for a real finding.
#[test]
fn completions_rejects_an_unknown_shell_with_2() {
    let assert = cargo_bin_cmd!("evnx")
        .args(["completions", "tcsh"])
        .assert()
        .code(2);

    let stderr = String::from_utf8_lossy(&assert.get_output().stderr).to_string();
    assert!(stderr.contains("No verdict"), "{stderr}");
    assert!(
        stderr.contains("bash"),
        "the error should name the valid shells: {stderr}"
    );
}

#[test]
fn completions_still_generates_for_a_known_shell() {
    for shell in ["bash", "zsh", "fish", "powershell"] {
        let assert = cargo_bin_cmd!("evnx")
            .args(["completions", shell])
            .assert()
            .code(0);
        assert!(
            !assert.get_output().stdout.is_empty(),
            "{shell} produced no completion script"
        );
    }
}
