//! Integration test to verify backward compatibility of `evnx init`.

use assert_cmd::Command;
use predicates::prelude::*;
use tempfile::TempDir;

#[test]
fn init_with_stack_flag_creates_expected_vars() {
    let dir = TempDir::new().unwrap();

    Command::cargo_bin("evnx")
        .unwrap()
        .arg("init")
        .arg("--stack")
        .arg("python")
        .arg("--services")
        .arg("postgresql,redis")
        .arg("--path")
        .arg(dir.path())
        .arg("--yes")
        .assert()
        .success()
        .stdout(predicate::str::contains("Created .env.example"));

    let content = std::fs::read_to_string(dir.path().join(".env.example")).unwrap();

    // Stack-specific vars
    assert!(content.contains("SECRET_KEY="));
    assert!(content.contains("DEBUG="));

    // Service-specific vars
    assert!(content.contains("DATABASE_URL="));
    assert!(content.contains("REDIS_URL="));

    // Footer
    assert!(content.contains("Generated by dotenv-space"));
}

#[test]
fn init_with_rust_stack_uses_double_underscore_format() {
    let dir = TempDir::new().unwrap();

    Command::cargo_bin("evnx")
        .unwrap()
        .arg("init")
        .arg("--stack")
        .arg("rust")
        .arg("--path")
        .arg(dir.path())
        .arg("--yes")
        .assert()
        .success();

    let content = std::fs::read_to_string(dir.path().join(".env.example")).unwrap();
    assert!(content.contains("APP__ENVIRONMENT="));
    assert!(content.contains("APP__PORT="));
}