// tests/common/assertions.rs

//! Custom predicates for test assertions.

use predicates::prelude::*;

pub fn has_env_vars(vars: &[&str]) -> impl Predicate<str> {
    let mut iter = vars.iter();

    // Use .boxed() to get a consistent BoxPredicate type
    let first = match iter.next() {
        Some(var) => predicate::str::contains(format!("{}=", var)).boxed(),
        None => return predicate::always().boxed(),
    };

    // Explicitly type the accumulator in the closure
    iter.fold(first, |acc, var| {
        acc.and(predicate::str::contains(format!("{}=", var)))
            .boxed()
    })
}

/// Predicate: Content has section header
pub fn has_section(name: &str) -> impl Predicate<str> {
    let name = name.to_string();
    predicate::function(move |s: &str| {
        s.contains(&format!("# ── {} ──", name)) || s.contains(&format!("# [ADDED] {}", name))
    })
}

/// Predicate: Content has generation footer
pub fn has_generation_footer() -> impl Predicate<str> {
    predicate::function(|s: &str| s.contains("# Generated by evnx v"))
}
