// ============================================================================
// formats/shell.rs
// ============================================================================

use crate::core::converter::{ConvertOptions, Converter};
use anyhow::Result;
// use std::collections::HashMap;
use indexmap::IndexMap;

pub struct ShellExportConverter;

impl Converter for ShellExportConverter {
    fn convert(&self, vars: &IndexMap<String, String>, options: &ConvertOptions) -> Result<String> {
        let filtered = options.filter_vars(vars);

        let mut output = String::new();
        output.push_str("#!/bin/bash\n");
        output.push_str("# Generated by evnx\n\n");

        for (k, v) in filtered.iter() {
            let key = options.transform_key(k);
            let value = options.transform_value(v);
            // ⛔ Single quotes, via the shared helper. This was
            // `value.replace('"', "\\\"")` inside double quotes, which left
            // `$(…)`, backticks and `$VAR` live — so the script this command
            // tells you to source executed whatever a value contained, lost
            // `pa$sw0rd` to an empty expansion, and failed `sh -n` outright on a
            // value ending in a backslash.
            output.push_str(&format!(
                "export {}={}\n",
                key,
                crate::formats::quoting::shell_single(value.as_str())
            ));
        }

        Ok(output)
    }

    fn name(&self) -> &str {
        "shell"
    }

    fn description(&self) -> &str {
        "Shell export script"
    }
}
