// ============================================================================
// formats/shell.rs
// ============================================================================

use crate::core::converter::{ConvertOptions, Converter};
use anyhow::Result;
use std::collections::HashMap;

pub struct ShellExportConverter;

impl Converter for ShellExportConverter {
    fn convert(&self, vars: &HashMap<String, String>, options: &ConvertOptions) -> Result<String> {
        let filtered = options.filter_vars(vars);

        let mut output = String::new();
        output.push_str("#!/bin/bash\n");
        output.push_str("# Generated by evnx\n\n");

        for (k, v) in filtered.iter() {
            let key = options.transform_key(k);
            let value = options.transform_value(v);
            // Escape quotes in values
            let escaped_value = value.replace('"', "\\\"");
            output.push_str(&format!("export {}=\"{}\"\n", key, escaped_value));
        }

        Ok(output)
    }

    fn name(&self) -> &str {
        "shell"
    }

    fn description(&self) -> &str {
        "Shell export script"
    }
}
