// ============================================================================
// formats/terraform.rs
// ============================================================================

use crate::core::converter::{ConvertOptions, Converter};
use anyhow::Result;
use std::collections::HashMap;

pub struct TerraformConverter;

impl Converter for TerraformConverter {
    fn convert(&self, vars: &HashMap<String, String>, options: &ConvertOptions) -> Result<String> {
        let filtered = options.filter_vars(vars);

        let mut output = String::new();
        output.push_str("# Generated by evnx\n\n");

        for (k, v) in filtered.iter() {
            let key = options.transform_key(k).to_lowercase();
            let value = options.transform_value(v);
            // Escape quotes and backslashes
            let escaped_value = value.replace('\\', "\\\\").replace('"', "\\\"");
            output.push_str(&format!("{} = \"{}\"\n", key, escaped_value));
        }

        Ok(output)
    }

    fn name(&self) -> &str {
        "terraform"
    }

    fn description(&self) -> &str {
        "Terraform .tfvars format"
    }
}
