// ============================================================================
// formats/terraform.rs
// ============================================================================

use crate::core::converter::{ConvertOptions, Converter};
use anyhow::Result;
// use std::collections::HashMap;
use indexmap::IndexMap;

pub struct TerraformConverter;

impl Converter for TerraformConverter {
    fn convert(&self, vars: &IndexMap<String, String>, options: &ConvertOptions) -> Result<String> {
        let filtered = options.filter_vars(vars);

        let mut output = String::new();
        output.push_str("# Generated by evnx\n\n");

        for (k, v) in filtered.iter() {
            let key = options.transform_key(k).to_lowercase();
            let value = options.transform_value(v);
            // ⛔ `${` and `%{` are HCL interpolation and directive markers, and
            // escaping only `\` and `"` left them live — so a value containing
            // `${…}` referred to a variable that does not exist and the
            // generated tfvars failed to load.
            output.push_str(&format!(
                "{} = {}\n",
                key,
                crate::formats::quoting::hcl_string(value.as_str())
            ));
        }

        Ok(output)
    }

    fn name(&self) -> &str {
        "terraform"
    }

    fn description(&self) -> &str {
        "Terraform .tfvars format"
    }
}
