//! Gitignore management utilities for the evnx core library.
//!
//! This module provides pure I/O helpers for locating, reading, and updating
//! `.gitignore` files. It is intentionally decoupled from any specific command
//! (template, init, etc.) and contains no CLI logic, TTY detection, or user
//! prompting — those concerns belong in the calling command module.
//!
//! # Responsibilities
//!
//! - Locating the git root and its `.gitignore` by walking ancestor directories
//! - Checking whether a path entry is already present in a `.gitignore`
//! - Appending new entries under a labelled `# ── evnx generated` section
//! - Computing output-relative paths suitable for `.gitignore` patterns
//!
//! # What this module does NOT do
//!
//! - TTY detection or interactive prompting — handle in the calling command
//! - Glob pattern matching (e.g. detecting that `*.toml` covers `config.toml`)
//!   — exact-line matching only; glob support is deferred to a future version
//! - Per-subdirectory `.gitignore` file scanning — only the root `.gitignore`
//!   is considered in the current implementation
//!
//! # Usage
//!
//! ```no_run
//! use std::path::Path;
//! use evnx::core::gitignore::{
//!     find_gitignore_path, relative_output_path, check_ignored,
//!     append_entry, GitignoreStatus,
//! };
//!
//! let start = Path::new("/project/services/api");
//!
//! if let Some(gitignore_path) = find_gitignore_path(start) {
//!     let git_root = gitignore_path.parent().unwrap();
//!     let output   = Path::new("/project/services/api/config.toml");
//!
//!     if let Some(entry) = relative_output_path(git_root, output) {
//!         let entry_str = entry.to_string_lossy();
//!         match check_ignored(&gitignore_path, &entry_str) {
//!             GitignoreStatus::AlreadyIgnored => { /* nothing to do */ }
//!             _ => {
//!                 append_entry(&gitignore_path, &entry_str).expect("write failed");
//!             }
//!         }
//!     }
//! }
//! ```

use anyhow::{Context, Result};
use std::fs;
use std::path::{Path, PathBuf};

// ─────────────────────────────────────────────────────────────────────────────
// Constants
// ─────────────────────────────────────────────────────────────────────────────

/// The section header written by evnx when it adds entries to `.gitignore`.
///
/// This exact string is used both when writing the section and when detecting
/// whether the section already exists. It must not be changed without a
/// migration path, as existing `.gitignore` files will contain this literal.
pub const SECTION_HEADER: &str =
    "# ── evnx generated ─────────────────────────────────────────";

/// The explanatory comment written immediately below [`SECTION_HEADER`].
const SECTION_COMMENT: &str =
    "# Files generated by `evnx template` may contain secrets — do not commit.";

// ─────────────────────────────────────────────────────────────────────────────
// Public types
// ─────────────────────────────────────────────────────────────────────────────

/// The result of checking whether a path entry is present in a `.gitignore`.
///
/// Returned by [`check_ignored`]. The caller should use this to decide whether
/// to call [`append_entry`] — `append_entry` is not idempotent on its own.
#[derive(Debug, PartialEq, Eq)]
pub enum GitignoreStatus {
    /// The entry was found as an exact line match (after trimming whitespace).
    /// No action needed.
    AlreadyIgnored,

    /// The `.gitignore` file exists but does not contain a matching entry.
    /// [`append_entry`] should be called to add the entry.
    NotIgnored,

    /// The `.gitignore` file does not exist yet.
    /// [`append_entry`] will create it.
    FileNotFound,
}

// ─────────────────────────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────────────────────────

/// Locate the `.gitignore` file for the git repository that contains `start`.
///
/// Walks the directory tree upward from `start`, looking for an entry named
/// `.git` at each level. Both `.git/` directories (standard repositories) and
/// `.git` files (git worktrees) are recognised. The `.gitignore` is expected
/// to reside in the same directory as the `.git` entry, even if it does not
/// exist yet — the returned path may refer to a file that has not been created.
///
/// Returns `None` if no git root is found before reaching the filesystem root.
///
/// # Arguments
///
/// * `start` - The directory from which to begin the upward walk. Typically
///   `std::env::current_dir()`. Does not need to exist; if it does not,
///   the walk begins at the nearest existing ancestor.
///
/// # Examples
///
/// ```no_run
/// use std::path::Path;
/// use evnx::core::gitignore::find_gitignore_path;
///
/// // Running from /project/services/api in a repo rooted at /project:
/// let path = find_gitignore_path(Path::new("/project/services/api"));
/// assert_eq!(path, Some(std::path::PathBuf::from("/project/.gitignore")));
/// ```
#[must_use]
pub fn find_gitignore_path(start: &Path) -> Option<PathBuf> {
    let mut current = start.to_path_buf();

    loop {
        if current.join(".git").exists() {
            return Some(current.join(".gitignore"));
        }

        // Move to the parent; stop if we have reached the filesystem root
        // (i.e. parent == current, which happens at "/" on Unix and "C:\" on Windows).
        match current.parent() {
            Some(parent) if parent != current => current = parent.to_path_buf(),
            _ => return None,
        }
    }
}

/// Compute the path of `output` relative to `git_root`, suitable for use as
/// a `.gitignore` pattern.
///
/// Both `git_root` and `output` should be **absolute** paths. If `output` is
/// relative, the caller is responsible for making it absolute (e.g. by joining
/// it with `std::env::current_dir()`) before passing it here.
///
/// Returns `None` if `output` is not under `git_root` — in that case the
/// `.gitignore` file cannot protect it, and the caller should warn the user.
///
/// # Arguments
///
/// * `git_root` - Absolute path to the root of the git repository (the
///   directory that contains `.git`).
/// * `output`   - Absolute path to the generated file to be ignored.
///
/// # Examples
///
/// ```
/// use std::path::Path;
/// use evnx::core::gitignore::relative_output_path;
///
/// let git_root = Path::new("/project");
/// let output   = Path::new("/project/k8s/configmap.yaml");
/// let entry    = relative_output_path(git_root, output).unwrap();
///
/// assert_eq!(entry.to_string_lossy(), "k8s/configmap.yaml");
/// ```
#[must_use]
pub fn relative_output_path(git_root: &Path, output: &Path) -> Option<PathBuf> {
    output
        .strip_prefix(git_root)
        .ok()
        .map(Path::to_path_buf)
}

/// Check whether `entry` is already present in the `.gitignore` at the given path.
///
/// Matching is **exact** (after trimming leading and trailing whitespace) and
/// **case-sensitive**, consistent with git's behaviour on Linux. Comment lines
/// (starting with `#`) and blank lines are ignored.
///
/// Note: this function performs an exact string comparison only. It does not
/// evaluate gitignore glob patterns — a `.gitignore` containing `*.toml` will
/// not be detected as covering `config.toml` by this function. Glob-aware
/// coverage detection is deferred to a future version.
///
/// # Arguments
///
/// * `gitignore_path` - Path to the `.gitignore` file to check. May not exist.
/// * `entry`          - The path pattern to search for (e.g. `"config.toml"`,
///   `"k8s/configmap.yaml"`).
///
/// # Errors
///
/// Returns an error only if the file exists but cannot be read.
///
/// # Examples
///
/// ```no_run
/// use std::path::Path;
/// use evnx::core::gitignore::{check_ignored, GitignoreStatus};
///
/// let status = check_ignored(Path::new(".gitignore"), "config.toml")
///     .expect("could not read .gitignore");
///
/// match status {
///     GitignoreStatus::AlreadyIgnored => println!("already protected"),
///     GitignoreStatus::NotIgnored     => println!("needs to be added"),
///     GitignoreStatus::FileNotFound   => println!("no .gitignore yet"),
/// }
/// ```
pub fn check_ignored(gitignore_path: &Path, entry: &str) -> Result<GitignoreStatus> {
    if !gitignore_path.exists() {
        return Ok(GitignoreStatus::FileNotFound);
    }

    let content = fs::read_to_string(gitignore_path).with_context(|| {
        format!(
            "Failed to read .gitignore at '{}'",
            gitignore_path.display()
        )
    })?;

    let matched = content
        .lines()
        .filter(|line| {
            let trimmed = line.trim();
            !trimmed.is_empty() && !trimmed.starts_with('#')
        })
        .any(|line| line.trim() == entry.trim());

    if matched {
        Ok(GitignoreStatus::AlreadyIgnored)
    } else {
        Ok(GitignoreStatus::NotIgnored)
    }
}

/// Add `entry` to the `.gitignore` at the given path, creating it if necessary.
///
/// Entries are grouped under a labelled `# ── evnx generated` section so they
/// are easy to identify and maintain. On the first call, the section header and
/// an explanatory comment are written; subsequent calls append inside the
/// existing section.
///
/// **This function is not idempotent.** Always call [`check_ignored`] first and
/// only call `append_entry` when the status is [`GitignoreStatus::NotIgnored`]
/// or [`GitignoreStatus::FileNotFound`].
///
/// # Arguments
///
/// * `gitignore_path` - Path to the `.gitignore` file. Created if it does not
///   exist; its parent directory must already exist.
/// * `entry`          - The path pattern to append (e.g. `"config.toml"`).
///
/// # Errors
///
/// Returns an error if the file cannot be read or written.
///
/// # Examples
///
/// ```no_run
/// use std::path::Path;
/// use evnx::core::gitignore::{check_ignored, append_entry, GitignoreStatus};
///
/// let path  = Path::new(".gitignore");
/// let entry = "config.toml";
///
/// if !matches!(check_ignored(path, entry).unwrap(), GitignoreStatus::AlreadyIgnored) {
///     append_entry(path, entry).expect("failed to update .gitignore");
/// }
/// ```
pub fn append_entry(gitignore_path: &Path, entry: &str) -> Result<()> {
    let content = if gitignore_path.exists() {
        fs::read_to_string(gitignore_path).with_context(|| {
            format!(
                "Failed to read .gitignore at '{}'",
                gitignore_path.display()
            )
        })?
    } else {
        String::new()
    };

    let updated = if content.contains(SECTION_HEADER) {
        insert_into_section(&content, entry)
    } else {
        append_new_section(&content, entry)
    };

    fs::write(gitignore_path, updated).with_context(|| {
        format!(
            "Failed to write .gitignore at '{}'",
            gitignore_path.display()
        )
    })?;

    Ok(())
}

// ─────────────────────────────────────────────────────────────────────────────
// Private helpers
// ─────────────────────────────────────────────────────────────────────────────

/// Insert `entry` inside the existing evnx section in `content`.
///
/// The section ends at the first blank line after the header, or at EOF.
/// The new entry is inserted at that boundary so it stays within the section.
fn insert_into_section(content: &str, entry: &str) -> String {
    let trailing_newline = content.ends_with('\n');
    let lines: Vec<&str> = content.lines().collect();

    // SAFETY: called only after confirming SECTION_HEADER is present in content.
    let header_idx = lines
        .iter()
        .position(|l| *l == SECTION_HEADER)
        .expect("SECTION_HEADER confirmed present before calling insert_into_section");

    // The section ends at the first blank line after the header, or at EOF.
    let section_end = lines[header_idx + 1..]
        .iter()
        .position(|l| l.trim().is_empty())
        .map(|offset| header_idx + 1 + offset)
        .unwrap_or(lines.len());

    let mut updated = lines.to_vec();
    updated.insert(section_end, entry);

    let mut result = updated.join("\n");
    if trailing_newline {
        result.push('\n');
    }
    result
}

/// Append a new evnx section containing `entry` to the end of `content`.
///
/// Ensures exactly one blank line separates the new section from any existing
/// content, and that the file ends with a trailing newline.
fn append_new_section(content: &str, entry: &str) -> String {
    // Determine the separator needed before the new section.
    let prefix = if content.is_empty() {
        // New file — no separator needed.
        ""
    } else if content.ends_with("\n\n") {
        // Already has a blank line — no additional separator.
        ""
    } else if content.ends_with('\n') {
        // Has a trailing newline but no blank line — add one blank line.
        "\n"
    } else {
        // No trailing newline at all — add newline + blank line.
        "\n\n"
    };

    format!(
        "{content}{prefix}{SECTION_HEADER}\n{SECTION_COMMENT}\n{entry}\n"
    )
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    // ── helpers ───────────────────────────────────────────────────────────────

    /// Create a temporary directory tree:
    ///   <root>/
    ///   <root>/.git/          (marks the git root)
    ///   <root>/sub/sub2/      (nested working directory)
    fn make_repo(tmp: &TempDir) -> (PathBuf, PathBuf) {
        let root = tmp.path().to_path_buf();
        fs::create_dir_all(root.join(".git")).unwrap();
        let nested = root.join("sub").join("sub2");
        fs::create_dir_all(&nested).unwrap();
        (root, nested)
    }

    // ── find_gitignore_path ───────────────────────────────────────────────────

    #[test]
    fn test_find_from_repo_root() {
        let tmp = TempDir::new().unwrap();
        let (root, _) = make_repo(&tmp);

        let result = find_gitignore_path(&root);
        assert_eq!(result, Some(root.join(".gitignore")));
    }

    #[test]
    fn test_find_from_nested_subdirectory() {
        let tmp = TempDir::new().unwrap();
        let (root, nested) = make_repo(&tmp);

        let result = find_gitignore_path(&nested);
        assert_eq!(result, Some(root.join(".gitignore")));
    }

    #[test]
    fn test_find_no_git_repo() {
        // A temp dir with no .git anywhere.
        let tmp = TempDir::new().unwrap();
        let result = find_gitignore_path(tmp.path());
        assert_eq!(result, None);
    }

    #[test]
    fn test_find_git_as_file_worktree() {
        // git worktrees use a .git FILE instead of a directory.
        let tmp = TempDir::new().unwrap();
        let root = tmp.path().to_path_buf();
        fs::write(root.join(".git"), "gitdir: /some/other/.git/worktrees/wt").unwrap();

        let result = find_gitignore_path(&root);
        assert_eq!(result, Some(root.join(".gitignore")));
    }

    #[test]
    fn test_find_gitignore_not_required_to_exist() {
        // find_gitignore_path returns the expected path even if the file
        // itself does not exist yet (it will be created by append_entry).
        let tmp = TempDir::new().unwrap();
        let (root, nested) = make_repo(&tmp);

        let result = find_gitignore_path(&nested).unwrap();
        assert_eq!(result, root.join(".gitignore"));
        assert!(!result.exists(), "file should not exist yet");
    }

    // ── relative_output_path ─────────────────────────────────────────────────

    #[test]
    fn test_relative_path_simple() {
        let root = Path::new("/project");
        let output = Path::new("/project/config.toml");
        let result = relative_output_path(root, output).unwrap();
        assert_eq!(result, PathBuf::from("config.toml"));
    }

    #[test]
    fn test_relative_path_subdirectory() {
        let root = Path::new("/project");
        let output = Path::new("/project/k8s/configmap.yaml");
        let result = relative_output_path(root, output).unwrap();
        assert_eq!(result, PathBuf::from("k8s/configmap.yaml"));
    }

    #[test]
    fn test_relative_path_outside_root_returns_none() {
        let root = Path::new("/project");
        let output = Path::new("/other/config.toml");
        let result = relative_output_path(root, output);
        assert_eq!(result, None);
    }

    #[test]
    fn test_relative_path_deeply_nested() {
        let root = Path::new("/project");
        let output = Path::new("/project/a/b/c/config.toml");
        let result = relative_output_path(root, output).unwrap();
        assert_eq!(result, PathBuf::from("a/b/c/config.toml"));
    }

    // ── check_ignored ─────────────────────────────────────────────────────────

    #[test]
    fn test_check_file_not_found() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join(".gitignore");
        // File does not exist
        let status = check_ignored(&path, "config.toml").unwrap();
        assert_eq!(status, GitignoreStatus::FileNotFound);
    }

    #[test]
    fn test_check_empty_file_is_not_ignored() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join(".gitignore");
        fs::write(&path, "").unwrap();
        let status = check_ignored(&path, "config.toml").unwrap();
        assert_eq!(status, GitignoreStatus::NotIgnored);
    }

    #[test]
    fn test_check_exact_match() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join(".gitignore");
        fs::write(&path, ".env\nconfig.toml\nnode_modules/\n").unwrap();
        let status = check_ignored(&path, "config.toml").unwrap();
        assert_eq!(status, GitignoreStatus::AlreadyIgnored);
    }

    #[test]
    fn test_check_no_match() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join(".gitignore");
        fs::write(&path, ".env\nnode_modules/\n").unwrap();
        let status = check_ignored(&path, "config.toml").unwrap();
        assert_eq!(status, GitignoreStatus::NotIgnored);
    }

    #[test]
    fn test_check_comment_line_is_not_a_match() {
        // A line like "# config.toml" must not be treated as a match.
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join(".gitignore");
        fs::write(&path, "# config.toml\n").unwrap();
        let status = check_ignored(&path, "config.toml").unwrap();
        assert_eq!(status, GitignoreStatus::NotIgnored);
    }

    #[test]
    fn test_check_whitespace_padded_entry_matches() {
        // "  config.toml  " in the file should match "config.toml".
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join(".gitignore");
        fs::write(&path, "  config.toml  \n").unwrap();
        let status = check_ignored(&path, "config.toml").unwrap();
        assert_eq!(status, GitignoreStatus::AlreadyIgnored);
    }

    #[test]
    fn test_check_blank_lines_not_false_positive() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join(".gitignore");
        fs::write(&path, "\n\n\n").unwrap();
        let status = check_ignored(&path, "").unwrap();
        // Even an empty entry should not match blank lines
        // (blank lines are filtered out before comparison)
        assert_eq!(status, GitignoreStatus::NotIgnored);
    }

    #[test]
    fn test_check_subdirectory_entry() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join(".gitignore");
        fs::write(&path, "k8s/configmap.yaml\n").unwrap();
        let status = check_ignored(&path, "k8s/configmap.yaml").unwrap();
        assert_eq!(status, GitignoreStatus::AlreadyIgnored);
    }

    // ── append_entry ─────────────────────────────────────────────────────────

    #[test]
    fn test_append_creates_file_when_missing() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join(".gitignore");
        assert!(!path.exists());

        append_entry(&path, "config.toml").unwrap();

        assert!(path.exists());
        let content = fs::read_to_string(&path).unwrap();
        assert!(content.contains(SECTION_HEADER));
        assert!(content.contains(SECTION_COMMENT));
        assert!(content.contains("config.toml"));
        assert!(content.ends_with('\n'), "file should end with newline");
    }

    #[test]
    fn test_append_to_existing_file_without_section() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join(".gitignore");
        fs::write(&path, ".env\nnode_modules/\n").unwrap();

        append_entry(&path, "config.toml").unwrap();

        let content = fs::read_to_string(&path).unwrap();
        // Original content preserved
        assert!(content.contains(".env"));
        assert!(content.contains("node_modules/"));
        // New section appended
        assert!(content.contains(SECTION_HEADER));
        assert!(content.contains("config.toml"));
        // Section appears after original content
        let header_pos = content.find(SECTION_HEADER).unwrap();
        let env_pos = content.find(".env").unwrap();
        assert!(header_pos > env_pos);
    }

    #[test]
    fn test_append_separator_when_file_ends_with_newline() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join(".gitignore");
        fs::write(&path, ".env\n").unwrap();

        append_entry(&path, "config.toml").unwrap();

        let content = fs::read_to_string(&path).unwrap();
        // There should be a blank line between existing content and the section.
        assert!(
            content.contains(".env\n\n"),
            "expected blank line before section; got:\n{content}"
        );
    }

    #[test]
    fn test_append_no_double_blank_when_file_ends_with_double_newline() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join(".gitignore");
        fs::write(&path, ".env\n\n").unwrap();

        append_entry(&path, "config.toml").unwrap();

        let content = fs::read_to_string(&path).unwrap();
        // Should not introduce a triple newline.
        assert!(
            !content.contains("\n\n\n"),
            "unexpected triple newline; got:\n{content}"
        );
    }

    #[test]
    fn test_append_second_entry_inside_section() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join(".gitignore");

        append_entry(&path, "config.toml").unwrap();
        append_entry(&path, "k8s/configmap.yaml").unwrap();

        let content = fs::read_to_string(&path).unwrap();

        // Both entries present
        assert!(content.contains("config.toml"));
        assert!(content.contains("k8s/configmap.yaml"));

        // Only one section header
        assert_eq!(
            content.matches(SECTION_HEADER).count(),
            1,
            "section header should appear exactly once"
        );

        // Second entry is inside the section (appears after header, not before)
        let header_pos = content.find(SECTION_HEADER).unwrap();
        let second_pos = content.find("k8s/configmap.yaml").unwrap();
        assert!(second_pos > header_pos);
    }

    #[test]
    fn test_append_section_mid_file_inserts_before_blank_line() {
        // Existing structure:
        //   .env
        //   # ── evnx generated ──
        //   config.toml
        //
        //   node_modules/
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join(".gitignore");
        let initial = format!(".env\n{SECTION_HEADER}\n{SECTION_COMMENT}\nconfig.toml\n\nnode_modules/\n");
        fs::write(&path, &initial).unwrap();

        append_entry(&path, "deploy.yaml").unwrap();

        let content = fs::read_to_string(&path).unwrap();

        // node_modules/ must still be present and after a blank line
        assert!(content.contains("\n\nnode_modules/"));
        // deploy.yaml must be inside the section, before node_modules/
        let deploy_pos = content.find("deploy.yaml").unwrap();
        let modules_pos = content.find("node_modules/").unwrap();
        assert!(deploy_pos < modules_pos, "deploy.yaml should precede node_modules/");
        // Only one section header
        assert_eq!(content.matches(SECTION_HEADER).count(), 1);
    }

    #[test]
    fn test_append_preserves_trailing_newline() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join(".gitignore");
        fs::write(&path, ".env\n").unwrap();

        append_entry(&path, "config.toml").unwrap();

        let content = fs::read_to_string(&path).unwrap();
        assert!(content.ends_with('\n'), "file should end with newline");
    }

    #[test]
    fn test_append_empty_file_no_leading_blank() {
        // Creating a .gitignore from scratch should not start with a blank line.
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join(".gitignore");

        append_entry(&path, "config.toml").unwrap();

        let content = fs::read_to_string(&path).unwrap();
        assert!(
            !content.starts_with('\n'),
            "file created from empty should not start with blank line"
        );
    }

    // ── integration: full workflow ────────────────────────────────────────────

    #[test]
    fn test_full_workflow_new_repo() {
        let tmp = TempDir::new().unwrap();
        let (root, nested) = make_repo(&tmp);
        let output = root.join("config.toml");

        // Simulate a generated output file
        fs::write(&output, "secret = true\n").unwrap();

        // Step 1: find the gitignore path
        let gitignore = find_gitignore_path(&nested).unwrap();
        assert_eq!(gitignore, root.join(".gitignore"));

        // Step 2: compute the relative entry
        let entry = relative_output_path(&root, &output).unwrap();
        let entry_str = entry.to_string_lossy().to_string();
        assert_eq!(entry_str, "config.toml");

        // Step 3: check current status
        let status = check_ignored(&gitignore, &entry_str).unwrap();
        assert_eq!(status, GitignoreStatus::FileNotFound);

        // Step 4: append the entry
        append_entry(&gitignore, &entry_str).unwrap();

        // Step 5: verify it is now detected as ignored
        let status = check_ignored(&gitignore, &entry_str).unwrap();
        assert_eq!(status, GitignoreStatus::AlreadyIgnored);
    }

    #[test]
    fn test_full_workflow_idempotent_via_check() {
        let tmp = TempDir::new().unwrap();
        let (root, _) = make_repo(&tmp);
        let gitignore = root.join(".gitignore");

        // First run
        append_entry(&gitignore, "config.toml").unwrap();
        // Second run — check first, then conditionally append
        if !matches!(
            check_ignored(&gitignore, "config.toml").unwrap(),
            GitignoreStatus::AlreadyIgnored
        ) {
            append_entry(&gitignore, "config.toml").unwrap();
        }

        let content = fs::read_to_string(&gitignore).unwrap();
        assert_eq!(
            content.matches("config.toml").count(),
            1,
            "entry should appear exactly once when check is used correctly"
        );
    }
}