// src/schema/formatter.rs

use anyhow::Result;
use std::collections::HashMap;

use crate::schema::models::{VarCollection, VarMetadata, VarSource};

/// Format as complete .env.example with section headers
/// Category order for the generated file.
///
/// Curated rather than alphabetical: a reader opening `.env.example` wants the
/// application's own settings before its third-party integrations.
const CATEGORY_ORDER: &[&str] = &[
    "Framework",
    "Application",
    "Security",
    "Database",
    "Cache",
    "Auth",
    "Storage",
    "Service",
    "Infrastructure",
    "CI/CD",
];

/// The body of a generated `.env.example` — sections, descriptions, values.
///
/// ⚠️ One function, because there used to be two that differed in ways nobody
/// chose. `format_env_example` wrote `# ── Database ──`, sorted categories by a
/// curated order and marked required variables; `format_addition` wrote
/// `# [ADDED] Database`, sorted alphabetically and dropped the required marker.
/// The same component reached the same file in two shapes depending on which
/// verb put it there.
fn format_sections(vars: &VarCollection) -> String {
    let mut content = String::new();

    let mut by_category: HashMap<Option<String>, Vec<(&String, &VarMetadata)>> = HashMap::new();
    for (name, meta) in &vars.vars {
        by_category
            .entry(meta.category.clone())
            .or_default()
            .push((name, meta));
    }

    let mut categories: Vec<_> = by_category.keys().collect();
    categories.sort_by(|a, b| {
        let rank_a = get_category_rank(a.as_deref(), CATEGORY_ORDER);
        let rank_b = get_category_rank(b.as_deref(), CATEGORY_ORDER);
        rank_a.cmp(&rank_b).then_with(|| a.cmp(b))
    });

    for category in categories {
        match category {
            Some(cat_name) => content.push_str(&format!("\n# ── {} ──\n", cat_name)),
            None => content.push_str("\n# ── General ──\n"),
        }

        if let Some(vars_in_cat) = by_category.get(category) {
            let mut sorted: Vec<_> = vars_in_cat.iter().collect();
            sorted.sort_by_key(|(name, _)| *name);

            for (name, meta) in sorted {
                // ⚠️ The required marker goes **above** the variable, folded into
                // its description.
                //
                // It used to be written as a line of its own *after* the
                // assignment, which left `  # (required)` floating between two
                // unrelated variables with nothing to say which one it described.
                // Appending it to the assignment instead is no better: `add`
                // wraps that line as `# TODO: NAME=value  # <-- Fill in real
                // value`, so the marker would land as a second `#` comment
                // inside the first.
                //
                // Shared by `init` and `add`, so both change together — which is
                // the point of them sharing a renderer.
                match (&meta.description, meta.required) {
                    (Some(desc), true) => content.push_str(&format!("# {} (required)\n", desc)),
                    (Some(desc), false) => content.push_str(&format!("# {}\n", desc)),
                    (None, true) => content.push_str("# (required)\n"),
                    (None, false) => {}
                }
                content.push_str(&format!("{}={}\n", name, meta.example_value));
            }
        }
        content.push('\n');
    }

    content
}

pub fn format_env_example(vars: &VarCollection, include_footer: bool) -> Result<String> {
    let mut content = format_sections(vars);

    if include_footer {
        content.push_str(&format!(
            "# Generated by evnx v{} on {}\n",
            env!("CARGO_PKG_VERSION"),
            chrono::Local::now().format("%Y-%m-%d %H:%M")
        ));
    }

    Ok(content)
}

/// Format the `.env` that `init` writes.
///
/// ⚠️ **Active assignments, not `# TODO:` comments.** This used to emit
/// `# TODO: DB_HOST=localhost` for every variable, which meant a parser reading
/// the generated `.env` saw *nothing*. `init` closes by telling you to run
/// `evnx validate`, and doing exactly that on the project `init` had just
/// created reported every variable missing:
///
/// ```text
/// 3. Run 'evnx validate' to check configuration     <-- so you do
///
/// ✗  Missing required variable: DATABASE_URL
/// ✗  Missing required variable: DB_HOST
/// ... all six                                        exit 1
/// ```
///
/// It also made `init`'s first instruction — "Edit .env and replace placeholder
/// values" — untrue, since there were no values in `.env` to replace.
///
/// `.env` and `.env.example` now carry the same assignments, so the two files
/// agree and `validate` reports what actually needs attention: a placeholder is
/// reported as a placeholder, which is the thing it can act on.
pub fn format_env_template(vars: &VarCollection) -> Result<String> {
    let mut content =
        String::from("# Generated by evnx. Replace the placeholder values below with real ones.\n");

    // Group by category
    let mut by_category: HashMap<Option<String>, Vec<(&String, &VarMetadata)>> = HashMap::new();
    for (name, meta) in &vars.vars {
        by_category
            .entry(meta.category.clone())
            .or_default()
            .push((name, meta));
    }

    // Same category ordering as format_env_example
    let category_order: &[&str] = &[
        "Framework",
        "Application",
        "Security",
        "Database",
        "Cache",
        "Auth",
        "Storage",
        "Service",
        "Infrastructure",
        "CI/CD",
    ];

    let mut categories: Vec<_> = by_category.keys().collect();
    categories.sort_by(|a, b| {
        let rank_a = get_category_rank(a.as_deref(), category_order);
        let rank_b = get_category_rank(b.as_deref(), category_order);
        rank_a.cmp(&rank_b).then_with(|| a.cmp(b))
    });

    for category in categories {
        match category {
            Some(cat_name) => content.push_str(&format!("\n# ── {} ──\n", cat_name)),
            None => content.push_str("\n# ── General ──\n"),
        }

        if let Some(vars_in_cat) = by_category.get(category) {
            let mut sorted: Vec<_> = vars_in_cat.iter().collect();
            sorted.sort_by_key(|(name, _)| *name);

            for (name, meta) in sorted {
                if let Some(desc) = &meta.description {
                    content.push_str(&format!("# {}\n", desc));
                }
                // ⚠️ The required marker goes **above** the assignment, the
                // same way `format_sections` places it — so the two files read
                // identically apart from their headers.
                if meta.required {
                    content.push_str("# (required - must be set)\n");
                }
                content.push_str(&format!("{}={}\n", name, meta.example_value));
            }
        }
    }

    Ok(content)
}

/// Format as minimal addition for appending to existing .env.example
pub fn format_addition(vars: &VarCollection) -> Result<String> {
    // The same sections `init` writes. `evnx add postgresql` and
    // `evnx init --with postgresql` put the same component in the same file, and
    // used to disagree about what that looked like.
    let mut content = format_sections(vars);

    // Kept: *when* something arrived is still worth recording, and unlike the old
    // `# [ADDED]` heading it does not change the shape of a section.
    content.push_str(&format!(
        "# Added by evnx add on {}\n",
        chrono::Local::now().format("%Y-%m-%d %H:%M")
    ));

    Ok(content)
}

/// Generate preview summary for interactive confirmation
pub fn generate_preview(vars: &VarCollection) -> String {
    let mut lines = vec![format!("{} variables", vars.vars.len())];

    // Count by source
    let mut by_source: HashMap<&str, usize> = HashMap::new();
    for meta in vars.vars.values() {
        let source = match &meta.source {
            VarSource::Framework(_) => "framework",
            VarSource::Service(_) => "service",
            VarSource::Infrastructure(_) => "infra",
            VarSource::BlueprintOverride => "override",
        };
        *by_source.entry(source).or_insert(0) += 1;
    }

    for (source, count) in by_source {
        lines.push(format!("  • {} ×{}", source, count));
    }

    // List categories (convert to owned Strings for join)
    let mut categories: Vec<String> = vars
        .vars
        .values()
        .filter_map(|m| m.category.clone())
        .collect();
    categories.sort();
    categories.dedup();

    if !categories.is_empty() {
        lines.push(format!("  Categories: {}", categories.join(", ")));
    }

    lines.join("\n")
}

/// Helper: Get sort rank for a category name
/// Returns index in priority list, or 999 for unknown categories
fn get_category_rank(category: Option<&str>, priority_order: &[&str]) -> usize {
    match category {
        Some(cat) => priority_order.iter().position(|&p| p == cat).unwrap_or(999),
        None => 999, // Unknown/None categories go last
    }
}
