// src/schema/formatter.rs

use anyhow::Result;
use std::collections::HashMap;

use crate::schema::models::{VarCollection, VarMetadata, VarSource};

/// Format as complete .env.example with section headers
pub fn format_env_example(vars: &VarCollection, include_footer: bool) -> Result<String> {
    let mut content = String::new();

    // Group by category
    let mut by_category: HashMap<Option<String>, Vec<(&String, &VarMetadata)>> = HashMap::new();
    for (name, meta) in &vars.vars {
        by_category
            .entry(meta.category.clone())
            .or_default()
            .push((name, meta));
    }

    // Define category priority order (as owned Strings for easy comparison)
    let category_order: &[&str] = &[
        "Framework",
        "Application",
        "Security",
        "Database",
        "Cache",
        "Auth",
        "Storage",
        "Service",
        "Infrastructure",
        "CI/CD",
    ];

    // Sort categories by priority, then alphabetically
    let mut categories: Vec<_> = by_category.keys().collect();
    categories.sort_by(|a, b| {
        let rank_a = get_category_rank(a.as_deref(), category_order);
        let rank_b = get_category_rank(b.as_deref(), category_order);
        rank_a.cmp(&rank_b).then_with(|| a.cmp(b))
    });

    // Output each category
    for category in categories {
        // Print category header
        match category {
            Some(cat_name) => content.push_str(&format!("\n# ── {} ──\n", cat_name)),
            None => content.push_str("\n# ── General ──\n"),
        }

        // Print variables in this category
        if let Some(vars_in_cat) = by_category.get(category) {
            let mut sorted: Vec<_> = vars_in_cat.iter().collect();
            sorted.sort_by_key(|(name, _)| *name);

            for (name, meta) in sorted {
                if let Some(desc) = &meta.description {
                    content.push_str(&format!("# {}\n", desc));
                }
                content.push_str(&format!("{}={}\n", name, meta.example_value));
                if meta.required {
                    content.push_str("  # (required)\n");
                }
            }
        }
        content.push('\n');
    }

    // Add footer
    if include_footer {
        content.push_str(&format!(
            "# Generated by evnx v{} on {}\n",
            env!("CARGO_PKG_VERSION"),
            chrono::Local::now().format("%Y-%m-%d %H:%M")
        ));
    }

    Ok(content)
}

/// Format as .env template with TODO comments
pub fn format_env_template(vars: &VarCollection) -> Result<String> {
    let mut content = String::from("# TODO: Replace placeholder values with real credentials\n");

    // Group by category
    let mut by_category: HashMap<Option<String>, Vec<(&String, &VarMetadata)>> = HashMap::new();
    for (name, meta) in &vars.vars {
        by_category
            .entry(meta.category.clone())
            .or_default()
            .push((name, meta));
    }

    // Same category ordering as format_env_example
    let category_order: &[&str] = &[
        "Framework",
        "Application",
        "Security",
        "Database",
        "Cache",
        "Auth",
        "Storage",
        "Service",
        "Infrastructure",
        "CI/CD",
    ];

    let mut categories: Vec<_> = by_category.keys().collect();
    categories.sort_by(|a, b| {
        let rank_a = get_category_rank(a.as_deref(), category_order);
        let rank_b = get_category_rank(b.as_deref(), category_order);
        rank_a.cmp(&rank_b).then_with(|| a.cmp(b))
    });

    for category in categories {
        match category {
            Some(cat_name) => content.push_str(&format!("\n# ── {} ──\n", cat_name)),
            None => content.push_str("\n# ── General ──\n"),
        }

        if let Some(vars_in_cat) = by_category.get(category) {
            let mut sorted: Vec<_> = vars_in_cat.iter().collect();
            sorted.sort_by_key(|(name, _)| *name);

            for (name, meta) in sorted {
                if let Some(desc) = &meta.description {
                    content.push_str(&format!("# {}\n", desc));
                }
                // Add TODO comment for .env file
                content.push_str(&format!("# TODO: {}={}\n", name, meta.example_value));
                if meta.required {
                    content.push_str("  # (required - must be set)\n");
                }
            }
        }
    }

    Ok(content)
}

/// Format as minimal addition for appending to existing .env.example
pub fn format_addition(vars: &VarCollection) -> Result<String> {
    let mut content = String::new();

    let mut by_category: HashMap<Option<String>, Vec<(&String, &VarMetadata)>> = HashMap::new();
    for (name, meta) in &vars.vars {
        by_category
            .entry(meta.category.clone())
            .or_default()
            .push((name, meta));
    }

    // Simple alphabetical sort for additions
    let mut categories: Vec<_> = by_category.keys().collect();
    categories.sort();

    for category in categories {
        match category {
            Some(cat_name) => content.push_str(&format!("\n# [ADDED] {}\n", cat_name)),
            None => content.push_str("\n# [ADDED] General\n"),
        }

        if let Some(vars_in_cat) = by_category.get(category) {
            let mut sorted: Vec<_> = vars_in_cat.iter().collect();
            sorted.sort_by_key(|(name, _)| *name);

            for (name, meta) in sorted {
                if let Some(desc) = &meta.description {
                    content.push_str(&format!("# {}\n", desc));
                }
                content.push_str(&format!("{}={}\n", name, meta.example_value));
            }
        }
    }

    content.push_str(&format!(
        "\n# Added by evnx add on {}\n",
        chrono::Local::now().format("%Y-%m-%d %H:%M")
    ));

    Ok(content)
}

/// Generate preview summary for interactive confirmation
pub fn generate_preview(vars: &VarCollection) -> String {
    let mut lines = vec![format!("📦 {} variables", vars.vars.len())];

    // Count by source
    let mut by_source: HashMap<&str, usize> = HashMap::new();
    for meta in vars.vars.values() {
        let source = match &meta.source {
            VarSource::Framework(_) => "framework",
            VarSource::Service(_) => "service",
            VarSource::Infrastructure(_) => "infra",
            VarSource::BlueprintOverride => "override",
        };
        *by_source.entry(source).or_insert(0) += 1;
    }

    for (source, count) in by_source {
        lines.push(format!("  • {} ×{}", source, count));
    }

    // List categories (convert to owned Strings for join)
    let mut categories: Vec<String> = vars
        .vars
        .values()
        .filter_map(|m| m.category.clone())
        .collect();
    categories.sort();
    categories.dedup();

    if !categories.is_empty() {
        lines.push(format!("  Categories: {}", categories.join(", ")));
    }

    lines.join("\n")
}

/// Helper: Get sort rank for a category name
/// Returns index in priority list, or 999 for unknown categories
fn get_category_rank(category: Option<&str>, priority_order: &[&str]) -> usize {
    match category {
        Some(cat) => priority_order.iter().position(|&p| p == cat).unwrap_or(999),
        None => 999, // Unknown/None categories go last
    }
}
